### ISSUE TITLE
[Bug]: Yimmenu interferes with autoshop contract mw NPCs, possibly others

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1055]
### Describe the bug

Yimmenu will prevent some NPCs from spawning during missions. 

### Steps To Reproduce

1. Quickjoin autoshop contract missions through in-game phone (not sure if bug is present as host but feel free to test)
2. If you get superdollar, data contract, or ecu contract: once the objective is obtained there will be a drive back to a location and normally there will be waves of merryweather NPCs sent after the players on their drive back. 
3. Most NPCs don't show up, so you have a relatively quiet drive back instead. 

### Expected Behavior

Waves of NPCs sent to stop you per the mission. 

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

Could possibly happen in other missions, but these are the main ones I quickjoin since there's no cooldown. Without yimmenu loaded I have no issues with normal mission behavior. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Is this issue still present after the fixes we made to missions?
