### ISSUE TITLE
[Request]: Angry fighter in the sky

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1111]
### Problem

Sometimes I notice in sessions flying planes without pilots and which can shoot at people

### Solution

Maybe you can add such an aircraft as a function to this menu. Still, this is not as terrifying a feature as, for example, crash

### Reason

I think it's a pretty fun feature and won't be too much of an annoyance to players.

**Comment by Rxann** [comment]
this could be very cool

**Comment by themilkman554** [comment]
Yeah something like this would be great https://www.reddit.com/r/Gta5Modding/comments/w5joha/what_menu_has_swastika_angry_planes_asking_for_a/

**Comment by Tayipc38** [comment]
> Yeah something like this would be great https://www.reddit.com/r/Gta5Modding/comments/w5joha/what_menu_has_swastika_angry_planes_asking_for_a/

Lol that looks terrifying. Seems to me this is just simple attacking peds in jets? Currently peds can be spawned as attackers but there are no vehicle options. Say that gets added, would the peds be attacking any player in sight or just targeted players?

**Comment by Rxann** [comment]
Was this added?

**Comment by Yimura** [comment]
> Was this added?

Yes through the squad spawner.

**Comment by Rxann** [comment]
Thanks
