### ISSUE TITLE
[Bug]: After the announcement of a cheater or an event in the chat, the chat is no longer visible and usable

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1131]
### Describe the bug

After the menu detects a cheater in the session, the menu announces him in the chat, but the chat is not displayed and you cannot write to it. The same situation with any announced event (kick crash, etc.)

### Steps To Reproduce

1.Turn on in reactions
2. Cheater detection
3. Announcement in chat

### Expected Behavior

The chat should be displayed correctly and it was possible to write to it

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by yasmasdas** [comment]
Probably obvious but posting it for clarification to people reading:
https://github.com/YimMenu/YimMenu/blob/9ccb77e8ebf9c0b8565a536d4121077d406e37d3/src/util/notify.hpp#L67
is where the problem is and the problem might just be that we aren't doing HAS_SCALEFORM_MOVIE_LOADED after requesting it.
