### ISSUE TITLE
[Bug]: The Block join checkbox disappears

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1135]
### Describe the bug

After adding a player to the database, after clicking Block joining and switching between players, the player's checkbox disappears.

### Steps To Reproduce

1. Add a player to the database
2. Block joining
3. Choose another player in the database
4. Return to the previous player
5. The selected checkbox Block joining is not selected

### Expected Behavior

Checkbox Block join must be selected

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Have you tried clicking the save button before switching off of the selected player?
