### ISSUE TITLE
[Bug]: Ped pool overload crash

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#1267]
### Describe the bug

New crash loops spawning ped on player, overfilling their ped pool, and prevents stacks.

all it is is sorta like this

Ped handle = PED::SPAWN_PED(no idea about type but model is trevor);
script::current()->yield(15000ms);
ENTITY::DELETE_ENTITY(&handle);

EDIT: seems that the model is unknown and being spoofed to trevor through model swapping. original model is one of the slods? However they appear to be changing the crash model or spoof model as i write this issue. 
### Steps To Reproduce

no steps

### Expected Behavior

Not crashing by starting to delete recently spawned peds when pedpool is close to full.

### Screenshots and/or Logs

```
cannot provide as crash prevents stacks
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by DayibBaba** [comment]
Deleting entities never quite worked as its meant to. Instead denying a sync from the owner would be preferable. And we'd have to replicate this in order to be sure we patched it, if the current prots already don't.

**Comment by TheGreenBandit** [comment]
> Deleting entities never quite worked as its meant to. Instead denying a sync from the owner would be preferable. And we'd have to replicate this in order to be sure we patched it, if the current prots already don't.

I know its a crash by prometheus, so anyone with access to that shit can replicate the crash.

**Comment by iswaxan** [comment]
Hopefully they patch it soon

**Comment by TheGreenBandit** [comment]
might be able to stop through pools, block entities through spawn limit

**Comment by Yimura** [comment]
We'll have to take a look at adding ratelimits to ped creation, if one person is creating more than 50 peds at a time on our position is most likely not legit. We should probably stop accepting their ped creation syncs, or ratelimit and start deleting some of the peds in our area.

**Comment by Yimura** [comment]
This is not a pool overflow, the actual crash has been fixed in YimMenu though.
