### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Jistx** [YimMenu/YimMenu#1269]
### Describe the bug

When I inject into GTA it instantly crashes. (No other info available)

[System specs if useful]
AMD Ryzen 7 7700x
MSI GTX 1080ti 11Gb
32GB DDR5 ram

### Steps To Reproduce

1. Open GTA
2. Go into story mode
3. Inject dll
4. yimmenu console panel window shows for a second as game crashes but says nothing on the panel.
5. Repeat process praying it works
6. it doesn't work and you ask about it in issues tab of the github page :(

### Expected Behavior

I expected the menu to load as it did before upgrading from intel to AMD

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

Please help with the issue if you know what the problem is, Sorry if this is already something that has been posted and solved.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by SkiddyToast** [comment]
Please open the Event Viewer (you can find it easily by searching in the Windows start menu). Then, on the left side, open Windows Logs->Application, there you can find the crash labeled as having an "Error" level and a source of "Application Error". Click on it and send the details in the text box (highlighted in the screenshot).
![image](https://user-images.githubusercontent.com/45642596/233239285-f40642d7-ef4a-42f4-93b5-3db5c06ae453.png)

**Comment by Yimura** [comment]
@Jistx could you respond, the more information we have the easier to reproduce the bug or try to fix it.

**Comment by Yimura** [comment]
Not enough information to replicate and resolve the issue, is it still a problem @Jistx? I will reopen if you're still having problems with this.
