### ISSUE TITLE
[Request]: Get IP information

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1333]
### Problem

In many free menus, I have seen the function of viewing the approximate location of the player by IP.

### Solution

I think you can add some api if possible. So that you can see the country and city of the player. Although it seems to me that this api is limited, at least I did not find an unlimited api. Although I think you can add some kind of database that will contain such data, but it seems to me that it will be large

### Reason

This will eliminate the need to constantly copy the player's IP and check his location on third-party sites. While you have the ability to see the player's language in-game, this is of course not the same effect. Although this way you can understand that this player uses vpn. Sometimes stupid schoolchildren griefers stop griefing when you say his location and scare him with the fact that you can ddos his router))

**Comment by Yimura** [comment]
So you want to dox a player’s location? I don’t think there could be any other reason to add such a feature other than to dox someone or scaring them.

Not sure I’d want such a thing in YimMenu thinking about the ways it’ll be used. Just kick the griefer if he’s annoying.
