### ISSUE TITLE
[Bug]: Compiling error

### ISSUE THREAD

**Issue by Bam810bam321** [YimMenu/YimMenu#1370]
### Describe the bug

On compiling the menu it will show a error saying internal compiler error its in hud_colors.cpp
and if anyone knows the fix.
I used cmake to generate a visual studio 2022 solution using the following command 

cmake -G "Visual studio 17 2022"

### Steps To Reproduce

1. Download Project Files
2. Generate Visual Studio Project Files with cmake command
3. open and compile in Visual Studio
4. see internal compiler error

### Expected Behavior

The compile into a direct link library file

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/67829250/510fa5cc-41ec-4ccd-b6f8-48391c1bf704)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Bam810bam321** [comment]
Ok so I fixed it using only 
cmake .
then opening the solution file

**Comment by Yimura** [comment]
Please see this setup guide, the way you're currently doing it won't work well to keep up when the repo updates.

https://github.com/YimMenu/YimMenu/blob/documentation/docs/SETUP.md

Also did you read the main readme? If you've already got Visual Studio, you just need to open the project as a local folder and it will set it up for you. Any reason you're doing it completely from the command line?

**Comment by Bam810bam321** [comment]
I am used to making visual studio projects from cmake command

**Comment by Yimura** [comment]
Well then you're on your own with figuring it out.

We're providing perfectly and easy to use solutions and other ones that differ from those means you're on your own.

**Comment by Bam810bam321** [comment]
I already figured it out thats why I closed it I just used "cmake ."
