### ISSUE TITLE
New windows version

### ISSUE THREAD

**Issue by jonathonIT** [YimMenu/YimMenu#1397]
### Solution

I uploaded a new exe version here: (You need to disable Windows Defender to work)
[REDACTED]

### Reason

I uploaded a new exe version here: (You need to disable Windows Defender to work)
[REDACTED]

**Comment by GeopJr** [comment]
That's malware.

If anyone downloaded it, make sure to enable your antivirus.

YimMenu is only officially available [on the releases page](https://github.com/YimMenu/YimMenu/releases/tag/nightly).
