### ISSUE TITLE
[Bug]: Issue with code

### ISSUE THREAD

**Issue by Vlhss** [YimMenu/YimMenu#1405]
### Describe the bug

![image](https://github.com/YimMenu/YimMenu/assets/106196444/21a97370-dd33-4841-b01b-baf1165fd17b)
I am experiencing issues with the translator service. The project builds just fine but the error is annoying and I have no idea how to make a new command since my yimmenu project is very old and out of date.

### Steps To Reproduce

-

### Expected Behavior

-

### Screenshots and/or Logs

-

### Store

Epic Games

### Additional context

-

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by takoyakiwhite** [comment]
Check code grammar, like )

**Comment by Vlhss** [comment]
> Check code grammar, like )

its not any logical errors tho, the project builds and works just fine. The code is directly from the repo and the error appears without any code changes from my end. I just copied the project with git, let cmake do its thing (in vs2022) and then build but when I open files I come across this.

**Comment by TheGreenBandit** [comment]
This is not an issue, it will still build. It's because of the translation service that causes this.

**Comment by Vlhss** [comment]
> This is not an issue, it will still build. It's because of the translation service that causes this.

Is there a way to get rid of the warning or no then?

**Comment by Yimura** [comment]
I've never seen this before, though I don't use Visual Studio anymore.

Currently I am using Visual Studio Code and it recognises the string literal correctly.

**Comment by Vlhss** [comment]
ide issues, I hadnt updates it for quite some time now. Forgot to close this issue
