### ISSUE TITLE
[Bug]: [FATAL/tunables_service.cpp:87] Failed to cache tunables pops up after injecting into game

### ISSUE THREAD

**Issue by Ounyat** [YimMenu/YimMenu#1442]
### Describe the bug

the mod menu worked fine but I closed it and pressed unload and ever since then it just says [FATAL/tunables_service.cpp:87] Failed to cache tunables and stays on the tab that shows fps and players in your lobby I have uninstalled and reinstalled both the mod menu and the xenos injector nothing works

### Steps To Reproduce

i loaded gta up
injected the mod menu 
pressed unload on the mod menu 
restarted my game
loaded it back up 
now it gets to [FATAL/tunables_service.cpp:87] Failed to cache tunables and stops after [INFO/tunables.hpp:25] Snow loaded

### Expected Behavior

idk

### Screenshots and/or Logs

```
<paste your logs here>
```
![Screenshot 2023-06-16 154207](https://github.com/YimMenu/YimMenu/assets/136861735/ae31842e-2410-45be-b24a-4b65a8030ea8)
![Screenshot 2023-06-16 153838](https://github.com/YimMenu/YimMenu/assets/136861735/c6e33cbb-09cd-4811-87d7-70042134114e)

### Store

Steam

### Additional context

im really not to sure whats going on and i need some help

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Shizzins** [comment]
Didn't the game just update a couple days ago?

**Comment by Ounyat** [comment]
yes but yimmenu still works its bugged for me tho

**Comment by MadG3yZ** [comment]
is this fixed yet?
