### ISSUE TITLE
[Bug]: upside down world

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1558]
### Describe the bug

The bug is quite rare, but still I wanted to ask if it is connected with YimMenu or is it a bug of the game itself? So this does not interfere, but still I wonder why this is happening or is it the work of other modders?

### Steps To Reproduce

1. Connect to a random session
2. Play for a while
3. See what is on the screen

### Expected Behavior

.

### Screenshots and/or Logs

```
<paste your logs here>
```
![pic](https://github.com/YimMenu/YimMenu/assets/136161998/cc84e92d-98af-4acf-bafd-3106a486bd04)

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by tupoy-ya** [comment]
It's just a modder spawning LOD props.

**Comment by iDominiqe** [comment]
this is just a script for the stand mod, it would be great to add it to the YimMenu 

https://www.guilded.gg/stand/groups/x3ZgB10D/channels/bae59c11-4c7a-4a77-9738-d3876a47c786/docs/302105
