### ISSUE TITLE
[Bug]: Lua tabs contain space on first line.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1670]
### Describe the bug

When creating a new tab in Lua, there is a space on the first line the user did not request. It causes alignment issues.

### Steps To Reproduce

`casino_gui = gui.get_tab("GUI_TAB_NETWORK"):add_tab("Casino")
casino_gui:add_text("Poker")
force_poker_cards = casino_gui:add_checkbox("Force all Players Hands to Royal Flush")
set_dealers_poker_cards = casino_gui:add_checkbox("Force Dealer's Hand to Bad Beat")`

### Expected Behavior

Poker should be aligned with the checkboxes.

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/100792176/6d8e1010-cdfb-4869-b083-3047a81cd2a4)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by DayibBaba** [comment]
It causes ocd issues as well.
