### ISSUE TITLE
[Bug]: Lua allows for unfettered access to the user's disk.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1680]
### Describe the bug

The Lua client within the project allows a potential attacker to write arbitrary data to the disk, potentially adding services and programs to the startup list.

### Steps To Reproduce

Use the IO library in Lua.

### Expected Behavior

The IO library should not be available to Lua scripts. Instead, a settings class should be exposed that uses a dedicated JSON file to store and retrieve data on the disk.

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/100792176/7a2a1fc9-5158-48f0-9f40-c2f27630017a)

### Store

Rockstar

### Additional context

sol.hpp loads lib::io, could just remove it.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by xiaoxiao921** [comment]
Can confirm, I have this fixed locally, just trying to tackle another Lua issue and I'll pr it
