### ISSUE TITLE
[Bug]: Debug Globals does not work and writes duplicate files.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1687]
### Describe the bug

The globals_service class seems to be writing the globals.json file twice, once to the YimMenu folder and once to GTA V's folder. If I try to use the globals_service interface through the Debug menu, I get wildly incorrect results.

### Steps To Reproduce

Debug -> Globals
Add.
Base Address: 262145 Offsets 1 Offset 1: 8458

Gives wildly incorrect value. Setting the value results in unexpected behavior.

### Expected Behavior

No globals.json file should be written to the GTA V folder and the Globals debug menu should work as expected.

### Screenshots and/or Logs

![image](https://github.com/YimMenu/YimMenu/assets/100792176/15e24f01-2598-4ac0-904d-2acc17724701)
![image](https://github.com/YimMenu/YimMenu/assets/100792176/c55923d7-54b7-4fe2-a742-5142c97e59ab)
![image](https://github.com/YimMenu/YimMenu/assets/100792176/44c38aa4-6796-4f1d-a162-a2a211fea755)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Fixed with #1696?
