### ISSUE TITLE
[Bug]: Noclip does not work in first person.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1719]
### Describe the bug

When noclip is enabled, the player is stuck in place while in first person.

### Steps To Reproduce

1. Enable Noclip.
2. Use first person camera.
3. Bug appears.

### Expected Behavior

The user should be able to move while in first person.

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment]
Should be an easy fix, on it.
