### ISSUE TITLE
Kicking God Mode Player

### ISSUE THREAD

**Issue by HellPortal** [YimMenu/YimMenu#175]
**Is your feature request related to a problem? Please describe.**
While doing quests, I want to open god mode and kick the player who ruined my game.

**Describe the solution you'd like**
Kicking the player while God Mode is active.

**Provide Reasoning**
Imagine a player who turns on god mode in your game and ruins your fun.

**Additional context**
This kick feature should only be available for players with god mode active.

**Comment by Yimura** [comment]
Impossible to detect because the game uses god mode for legit reasons, thus you'd just start kicking players entering missions, going in interiors, in cutscenes, etc....

**Comment by HellPortal** [comment]
> Impossible to detect because the game uses god mode for legit reasons, thus you'd just start kicking players entering missions, going in interiors, in cutscenes, etc....


Yes you are right. I thought of something like this so that this feature is not abused, but as you said, this is not possible.

**Comment by Yimura** [comment]
It might be possible to detect, just not easy, you'd need to check a lot of stuff.
