### ISSUE TITLE
[Bug]: Personal Vehicle spawn does not work during missions.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1769]
### Describe the bug

If you try to spawn one of your personal vehicles during a mission, it refuses to spawn, or if it does it gets deleted I can't tell.

### Steps To Reproduce

1. Start a mission or a heist.
2. Spawn personal vehicle.
3. Bug appears.

### Expected Behavior

You should be able to spawn your personal vehicle during missions.

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by DayibBaba** [comment]
Can you spawn a clone?

**Comment by gir489returns** [comment]
> Can you spawn a clone?

What do you mean? I can spawn a persist vehicle, but because the personal vehicle spawning system is basically just abusing the mechanic, I presume the mission script is just checking if your real personal vehicle is in the world, then deleting it. We either need to disable that check, or spoof it so it thinks the personal vehicle is not a personal vehicle while on missions.

**Comment by Yimura** [comment]
Basically, freemode needs to be running to have personal vehicles spawn in a mission.

If you enable the clone vehicle feature it'll make an exact clone of the vehicle without the personal vehicle identifier.
