### ISSUE TITLE
[Bug]: Yim causes mission corruption despite having no protections on.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1788]
### Describe the bug

Similar to #899, although #899 is a red herring, something Yim is hooking/doing is causing missions to corrupt and get stuck in a state of perpetual loading. I have confirmed this 8 times in a row with someone, and then the 9th time, I didn't have Yim injected, we were able to proceed with the mission and didn't get stuck. I had this previous behavior with BBv2, so it might just be par for the course, but I was hooking a lot of the same things you were and checking for network tampering too, so it's probably the cause and effect of that. #1785 addresses at least the superficial complaints of #899, however the core issue remains of getting stuck in a perpetual loop. 

### Steps To Reproduce

Inject YIm.
Try to complete Casino Heist - The Big Con.
Bug Appears.

### Expected Behavior

Shouldn't get stuck loading forever.

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by UltraStuff** [comment]
Can confirm I have the same issue in the same exact heist. Also have the issue of people that I usually play with get teleported to random places when I didn't do nothing

**Comment by gir489returns** [comment]
@UltraStuff We're having trouble creating a reliable test case. I set every single hook to call the original during a cutscene or loading, and the bug still occurred. We thought maybe it's the init_native_tables hook, took that out, it worked. So as a good scientist, we thought it should be repeatable. Put the init_native_tables hook back in, and then the heist worked still. It feels like it works when it wants to, and there isn't a repeatable way to get the bug to occur.

**Comment by gir489returns** [comment]
It seems the change in #1785 does fix the initial problem, however, another lock occurs later when the police arrive during the same heist.
