### ISSUE TITLE
[Bug]: entering another player's vehicle removes their bulletproof tires

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1805]
### Describe the bug

entering another player's vehicle removes their bulletproof tires

### Steps To Reproduce

enter another player's vehicle, get wanted level, watch bulletproof tires get shot out

### Expected Behavior

to not remove their bulletproof tires

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
We’re gonna need your config for this to know what options you have on.
