### ISSUE TITLE
💡 [Animations]

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#187]
**Is your feature request related to a problem? Please describe.**
👎

**Describe the solution you'd like**
   [Self]
         ↳ [Animations]

**Provide Reasoning**
They're always nice to have, for various reasons, and it would be safer and easier than loading an outdated SP ASI.

**Additional context**
_e.g. : Add a premade list, and/or "Play by name" + "Save & Load / Favorite" buttons._

**Comment by Tayipc38** [comment]
The animation list can be fetched with a similar fashion as the vehicles.json. 
https://raw.githubusercontent.com/DurtyFree/gta-v-data-dumps/master/animDictsCompact.json

**Comment by epicmusicpt** [comment]
yeah animations would be nice!

**Comment by BUZZARDGTA** [comment]
It's been a while since this request is opened, would appreciate a work on it

**Comment by epicmusicpt** [comment]
will this ever be added to the menu?

**Comment by Yimura** [comment]
> will this ever be added to the menu?

Maybe, maybe not, I’m certainly not working on it currently and probably won’t in the future.
The issue is here for others that may see and have the skills to add such a feature to YimMenu.

**Comment by Aure7138** [comment]
> will this ever be added to the menu?

So far everything is fine except for resolving hardcoded animation names, I may try to complete the peds name first and then consider this.

**Comment by epicmusicpt** [comment]
ok,thanks for the info, i hope you guys can make it one day.

**Comment by Tayipc38** [comment]
> > will this ever be added to the menu?
> 
> So far everything is fine except for resolving hardcoded animation names, I may try to complete the peds name first and then consider this.

How about the cache system

**Comment by nikhilnayyar002** [comment]
i can see there is an animation tab in debug window. can we provide input or change animation timing to infinite. we already have a stop button there.

**Comment by lonelybud** [comment]
i can see there is an animation tab in debug window. can we provide input or change animation timing to infinite. we already have a stop button there in order to stop

**Comment by Yimura** [comment]
@DayibBaba is working on a user friendly interface here: #1668
