### ISSUE TITLE
[Bug]: auto desync kick or block not working with huge player database

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1878]
### Describe the bug

When some player that exists in the database of players and his connection is blocked when connecting to this player, auto desync kick does not work. It seems to me that this may be due to the fact that I already have 979 players in the json file and most of them are blocked. Moreover, I noticed that those who are at the beginning of the list are blocked from joining or an auto desync kick is sent, and those in the middle and at the end are simply displayed in red in the list of session players but are not blocked from joining and there is no auto desync for them. I noticed this when, after a certain moment, sound spammers with the letter N or V began to connect to me, which are somewhere in the middle of the base. I don't get any notifications about trying to block or desync a kick from this player

### Steps To Reproduce

1. Add a lot of players 900+ to DB
2. Block them from joining
3. Watch how those in the middle or end of the database are not blocked or autokicked

### Expected Behavior

Block-joined players should be blocked regardless of the size of the database and their place in the database itself.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by spinoza-spinoza** [comment]
wawww 900  player to block i think its better to use  block   RID joining  in setting  protection

**Comment by spinoza-spinoza** [comment]
when  i want to join some player (modder)    he  oem cick me and end session kick  then i auto desync  when joinying  session 
i see all list of players session   but  i auto desync

**Comment by ghost** [comment]
> wawww 900 player to block i think its better to use block RID joining in setting protection

The fact is that, for example, sound spammers can still come to me as a random open session, as well as other cheaters from the block list. they do not connect specifically to my RID. Although they should be blocked from joining when I'm the host, it doesn't, and if I'm not the host, an auto-desync kick should be sent. But the autodesync kick starts working only after it is connected and starts immediately trying to kick me or do something else with me
