### ISSUE TITLE
[Bug]: Vehicle -> Handling's sliders are awfully imprecise.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1903]
### Describe the bug

When trying to use any of the sliders, they just seem to shift between 0 and 10 and nothing in-between.

### Steps To Reproduce

Go to Vehicle -> Handling.
Change sliders.

### Expected Behavior

Should use a gradient.

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GTMoraes** [comment]
This is not very clear. There's definitely a gradient on some sliders. 
I do agree, however, that there are some sliders that are exaggerated, such as the acceleration slider. it goes from 0.010 to 10.000 in 1.000 steps, when it should go from 0.010 steps or at least 0.100 steps.

As I extensively use them, I can attest that several other sliders, the majority in fact, are perfectly fine.

**Comment by gir489returns** [comment]
@GTMoraes 

https://youtu.be/3esPj-CDLNc

**Comment by GTMoraes** [comment]
> @GTMoraes This ticket was really just to attach a commit to because I already know what the issue is, but since you seem so interested, here is the behavior of the bug.
> 
> https://youtu.be/3esPj-CDLNc

Cool! I'm not a programmer, but a tinkerer. I understood what you did. IIRC there are some other sliders that I'm not comfortable by how sensitive they are, and I'll probably try fixing them on my fork, and if good, I'll try pushing it here.

**Comment by gir489returns** [comment]
> Cool! I'm not a programmer, but a tinkerer. I understood what you did.

The parameters were backwards, it was a bug.
