### ISSUE TITLE
[Bug]: #1794 broke #1768

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1905]
### Describe the bug

When you leave the vehicle, godmode should still be applied to prevent assholes from blowing up your car. If this breaks something else, then a user-selected Boolean should be used to determine the behavior of exiting the vehicle. 

### Steps To Reproduce

1

### Expected Behavior

1

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Fixed in #1907
