### ISSUE TITLE
[Bug]: Firstperson noclip is inverted in all directions.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#1917]
### Describe the bug

When using noclipping in first person, the controls are completely backwards. Forwards sends you backwards, backwards sends you forwards, left sends you right and right sends you left. #1791 originally had fixed the issue, but some subsequent code to fulfill nonsense requirements of velocity setting seems to have broken it again.

### Steps To Reproduce

Enable noclip in first person.

### Expected Behavior

Should noclip like in third person but in first person.

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
No idea, when I fixed the issue it was fine, I don't even know who added the bad code after the fact.

**Comment by gir489returns** [comment]
> No idea, when I fixed the issue it was fine, I don't even know who added the bad code after the fact.

The bug occurs when the not aiming scenario does. It was introduced when @Yimura made you revert the code back to the velocity method for some stupid reason. Setting the velocity in first person mode doesn't work. I added a simple check to see if the player is aiming or if they're in first person mode. I don't know why setting the velocity matters so much, the network interp code can't possibly run that fast anyway.
