### ISSUE TITLE
[Improvement/Bug]: Infinite Range makes projectiles go zoom

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#1944]
### Which feature

Self -> Weapons -> Infinite Range

### Reason

When enabled projectiles (granates, sticky bomb, you know the deal) fly really far compared to when infinite range is disabled.

What i want: Only run infinite range when the target weapon is not a projectile

### Additional context

It was how i wanted with infinite range disabled

**Comment by TheGreenBandit** [comment]
Thats the point of the feature tho?

**Comment by pierrelasse** [comment]
Not really, it should make bullets fly infinitely but not projectiles. They should make a setting called Far Throw if you want to have what i dont want.

**Comment by pierrelasse** [comment]
s

**Comment by pierrelasse** [comment]
s
