### ISSUE TITLE
[Bug]: Ability bar is always set to value instead of max value

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#1945]
### Describe the bug

The ability bar (yellow thing. that when you use oppressor mk2 as example) is set to a value (usally max) when Vehicle -> Fun Features -> Boost Behavior is set to Instant Refill. The problem is that when the max value of the ability bar is higher then default it is stuck somewhere not full.

### Steps To Reproduce

Set Vehicle -> Fun Features -> Boost Behavior to Instant Refill
Get an oppressor mk2 try to boost. It works all good
Go to Vehicle -> Spawn Vehicle -> New -> Search for "RM-10 Bombushka" and spawn (enable noclip first so it can't explode)
Add Start boost or Starthelp (via hangar) idk what its called in english.
Use the startboost (you can't because yellow bar is stuck)

### Expected Behavior

Ability bar is maxed. (Other fix would be to add "Set to value" mode or something like that)

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Fixed in #2511
