### ISSUE TITLE
[Improvement]: NoClip automatic invisibility

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#1947]
### Which feature

It would be cool if there is an option that makes the vehicle and/or the player invisible when noclip is enabled.

Another request in the request: It would be also cool if you could make noclip -> no so that the vehicle still has collision (again in the noclip settings)

### Reason

QOL + shouldn't be too hard to make right? :^)

**Comment by spinoza-spinoza** [comment]
hi ..what mean noclip and what is for ?i always see it and i dont know when we use it

**Comment by pierrelasse** [comment]
NoClip how the name suggests, makes it so you have no collision and makes you fly so thst you csn fly through buildings any other things.

**Comment by spinoza-spinoza** [comment]
tank you ..i try it today its good  option
