### ISSUE TITLE
[Improvement]: "Log to console" setting in chatlog

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#1949]
### Describe the bug

If i have Network -> Chat - Log Chat Messages & Log Text Messages enabled, in the console nothing appears related to a chat message even tho messages appear in the normal chat.

### Steps To Reproduce

Enable Network -> Chat - Log Chat Messages & Log Text Messages
Get someone else to send a chat message

### Expected Behavior

Chat message gets logged to the like e.g. [00:00:00.00][INFO/chat_log.cpp:-1] your_mom: this is a chat message!

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by maybegreat48** [comment]
Chat messages are logged in `%APPDATA%/YimMenu/chat.log`

**Comment by pierrelasse** [comment]
Oh ok but could someone make a option to also log it to console? (shoulnt be to hard. plz)
This is then a improvement request.
