### ISSUE TITLE
[Request]: (Low Prio) Display who is talking in voicechat

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#1952]
### Problem

I can't see who is currently talking in voicechat.

### Solution

Add a list of the players that are talking (receiving sound from) to a list that is displayed through the In-Game Overlay or through an external list.

### Reason

See Problem

### Additional context

This is not important and just QOL and will not used much so the effort is worthless (kinda i think)

**Comment by gir489returns** [comment]
Press Z.

**Comment by pierrelasse** [comment]
Does it get displayed in the playerlist? If yes thx i guess.

**Comment by pierrelasse** [comment]
> Press Z.

Z or open the playerlist? Because i have the playerlist bound to y and if i open it while someone is currently talking in vc, no speaker icon whatsoever gets displayed in the playerlist.
