### ISSUE TITLE
[Request]: Remote Repair Vehicle

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#1954]
### Problem

I can destory a vehicle remotely but i also wantto repair it :D

### Solution

Add <player> -> Vehicle -> Repair Vehicle

### Reason

See Problem

**Comment by Tayipc38** [comment]
Tbf, repair should also be listed in the context menu.

**Comment by pierrelasse** [comment]
https://github.com/YimMenu/YimMenu/pull/1962
