### ISSUE TITLE
[Bug]: VK_RCONTROL, VK_RMENU hotkeys don't seem to work with noclip

### ISSUE THREAD

**Issue by womblee** [YimMenu/YimMenu#1998]
### Describe the bug

I change the hotkey to right control in settings, yet nothing happens

But it fully works on numpad 5 button for example.

### Steps To Reproduce

1. Go to settings->hotkeys
2. Toggle Noclip = VK_RCONTROL (Right control)
3. Try it
4. Doesn't work

### Expected Behavior

Should enable noclip

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by pierrelasse** [comment]
+1
Same with mouse keys (small ones at side)

**Comment by xiaoxiao921** [comment]
Duplicate of #3436
