### ISSUE TITLE
[Request]: Force Personal Vehicle during mission.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2008]
### Problem

The Toreador was allowed to be used during all Heist missions and certain Contact Missions, just like the Vigilante, but this feature has been disabled following the Los Santos Drug Wars update.

It was the most OP car to use for missions, because it could boost, hold all 4 people and it could fire missiles. Obviously, we could just spawn it in, but that would be obvious we are hacking. If we could somehow hijack the Personal Vehicle spawned and force it to another PV, that would be a good way to subtly spawn the car without people noticing.

### Solution

Hijack the personal vehicle global and set it to an arbitrary one the user selects, hopefully that will accomplish this.

### Reason

Heists go brrrrrrrr.

**Comment by ScottiePimp** [comment]
How are these vehicles chosen? Through mechanic in the mission or through a interaction-menu-selection before the mission starts?

Either way its just a global/local to patch the check, not hard at all to implement. However if there are hard-coded hash checks you would need to do it like you explained, hijack the global. Alternatively you could possibly also achieve this through model swapping.

**Comment by NjuuOwO** [comment]
Found this within `fm_mission_controller`, not sure if it useful

>Global_262145.f_30348 /* Tunable: ENABLE_VEHICLE_TOREADOR */
> Global_262145.f_30331 /* Tunable: LAUNCHPOSIX_TOREADOR */
> Global_262145.f_25735 /* Tunable: ENABLE_TOREADOR_CREATORS */

**Comment by ScottiePimp** [comment]
> Found this within `fm_mission_controller`, not sure if it useful
> 
> > Global_262145.f_30348 /* Tunable: ENABLE_VEHICLE_TOREADOR _/
> > Global_262145.f_30331 /_ Tunable: LAUNCHPOSIX_TOREADOR _/
> > Global_262145.f_25735 /_ Tunable: ENABLE_TOREADOR_CREATORS */

Those are not related to his request

**Comment by gir489returns** [comment]
> How are these vehicles chosen? Through mechanic in the mission or through a interaction-menu-selection before the mission starts?
> 
> Either way its just a global/local to patch the check, not hard at all to implement. However if there are hard-coded hash checks you would need to do it like you explained, hijack the global. Alternatively you could possibly also achieve this through model swapping.

It looks like func_8429 in fm_mission_controller checks your car against a blacklist and if it's found, you're not allowed to use it. 

func_8423 is the blacklist function.

When you start the mission, or more accurately, are queued to start the mission, you're presented with a menu to select your personal vehicle. I can't select the Toreador from this menu.

**Comment by gir489returns** [comment]
Even if you spawn in the vehicle or force it by writing to https://github.com/YimMenu/YimMenu/blob/81e43b51d7049a40b49d826d09bdc3828b1c7bb3/src/util/mobile.hpp#L23 the game will delete the car the next frame. See: #1769

**Comment by gir489returns** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/100792176/845d23a9-e3d5-47e4-ae23-61fb60d34a60)

I got it working. All banned vehicles can now be used in missions/heists.

**Comment by gir489returns** [comment]
> Found this within `fm_mission_controller`, not sure if it useful
> 
> > Global_262145.f_30348 /* Tunable: ENABLE_VEHICLE_TOREADOR _/
> > Global_262145.f_30331 /_ Tunable: LAUNCHPOSIX_TOREADOR _/
> > Global_262145.f_25735 /_ Tunable: ENABLE_TOREADOR_CREATORS */

Just FYI those tuneables allow the vehicle to be purchased. LAUNCHPOSIX is the date when the car is available for purchase, and ENABLE_VEHICLE allows you to drive it. ENABLE_TOREADOR_CREATORS allows you to use it on the race creator.

**Comment by NjuuOwO** [comment]
> I got it working. All banned vehicles can now be used in missions/heists.

Imagine spawning with avenger as PV lol
