### ISSUE TITLE
[Bug]: Unable to spawn Arbiter GT

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2037]
### Describe the bug

When attempting to use the Spawn Vehicle feature, the Arbiter GT appears in the list as a valid vehicle, however you cannot preview it or spawn it, despite it being a valid vehicle.

### Steps To Reproduce

1. Go to Spawn Vehicle.
2. Select Arbiter GT.
3. Bug appears.

### Expected Behavior

Should be able to preview and spawn the Arbiter GT.

### Logs and/or screenshots

[vehicles.zip](https://github.com/YimMenu/YimMenu/files/12448114/vehicles.zip)

https://github.com/YimMenu/YimMenu/assets/100792176/201aad0b-546c-4410-a542-c98f3c97da71

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by V1RU513N** [comment]
only next gen consoles have it

**Comment by gir489returns** [comment]
> only next gen consoles have it

Interesting. The YFT seems to be a placeholder, and the vehicles.meta make no mention of it being an invalid vehicle. How can we determine when loading the vehicles.meta if the vehicle doesn't belong on PC?

**Comment by xiaoxiao921** [comment]
we could do it at the file level by checking if it's come from a specific rpf

**Comment by ScottiePimp** [comment]
> > only next gen consoles have it
> 
> Interesting. The YFT seems to be a placeholder, and the vehicles.meta make no mention of it being an invalid vehicle. How can we determine when loading the vehicles.meta if the vehicle doesn't belong on PC?

You have to manually hash check it.

These are the invalid models from the E&E update:

cyclone2
ignus2
astron2
arbitergt
s95

**Comment by Yimura** [comment]
Isn't it just possible to skip them through the DLC hash? Like we've done with the following DLC:
https://github.com/YimMenu/YimMenu/blob/e58f9610b37847974c69324e89b6353973edac3f/src/services/gta_data/gta_data_service.cpp#L278-L281

**Comment by ScottiePimp** [comment]
I don't think that will alter the vehicle pool.

**Comment by xiaoxiao921** [comment]
> Isn't it just possible to skip them through the DLC hash? Like we've done with the following DLC:
> 
> https://github.com/YimMenu/YimMenu/blob/e58f9610b37847974c69324e89b6353973edac3f/src/services/gta_data/gta_data_service.cpp#L278-L281

It should, skip the vehicles that ScottiePimp listed, for reference this is the where the vehicle meta data is stored
`update/x64/dlcpacks/mpg9ec/dlc.rpf/common/data/levels/gta5/vehicles.meta`

**Comment by xiaoxiao921** [comment]
Oh nevermind, just realized that if branch is only for .setup file, then yeah the easy fix is to add this if branch also under the vehicles.meta parsing code

**Comment by NjuuOwO** [comment]
> cyclone2 ignus2 astron2 arbitergt s95

And that's all models that won't spawn
