### ISSUE TITLE
[Bug]: Same Name bug in scripts

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2041]
### Describe the bug

When i add a button called "Abc" which logs 1 to the console and i have another button called "Abc" which logs 2 to the console, the first button works and the second one does nothing.

Code (example):
```
local tab = gui.get_tab("test")
tab:add_button("Abc", function()
    log.info("1")
end)
tab:add_button("Abc", function()
  log.info("2")
end)
```

### Steps To Reproduce

Make a new script
Put the code from above into the script file
Load the script
Go in "test" category
Click first "Abc" button and see a "1" in the console
Click second "Abc" button and see nothing new appear in the console

### Expected Behavior

It logs 2 to the console

### Store

Epic Games

### Additional context

This is also for multiple tabs like if you have your own tab and add the subtab called "Self" it just doesnt work unless you rename it to something else. This applies to everything that has a name (buttons, tabs, etc.).

Plz fix because this is very annoying

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Please read on how ImGui works, you need to either add an ID in the label or use the push and pop id functionality.

https://github.com/ocornut/imgui/issues/74

**Comment by pierrelasse** [comment]
Can you link zhid then in the docs because if somone else has this problem there gonna make a new issue sgain.
