### ISSUE TITLE
[Request]: Script Key press listener

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2043]
### Problem

I want to have a custom bind to do something in my script but there is no way currently of doing so.

### Solution

Add (or something like that)
```
event.register_handler(menu_event.OnKeyPress, function(char, key)
  if key_code == "KEY_R" then -- I have no plan how keys will be named if with numbers or strings idk up to you
    log.info("You just pressed R!")
  end
end)
```

### Reason

See problem

### Additional context

It would be also super cool if you could add a listener like in buttons to a checkbox
```
tab:add_button("a", function()
end)

tab:add_checkbox("a", function(enabled)
end)
```

**Comment by Harmless05** [comment]
I did it by looping the script and then listening for PAD.IS_CONTROL_PRESSED(0, BUTTON.ID)

edit: link for button ids here https://docs.fivem.net/docs/game-references/controls/

**Comment by gir489returns** [comment]
> I did it by looping the script and then listening for PAD.IS_CONTROL_PRESSED(0, BUTTON.ID)

Certain scripts can disable the button press and you will not get a callback even if you are expecting one and can lead to phantom return values. Using PAD::IS_DISABLED_CONTROL_PRESSED will ensure you always get a proper return value, even if a script has disabled the action.

**Comment by pierrelasse** [comment]
> > I did it by looping the script and then listening for PAD.IS_CONTROL_PRESSED(0, BUTTON.ID)
> 
> Certain scripts can disable the button press and you will not get a callback even if you are expecting one and can lead to phantom return values. Using PAD::IS_DISABLED_CONTROL_PRESSED will ensure you always get a proper return value, even if a script has disabled the action.

Will this only return true if a disabled control is pressed or also if it's not?
Also now i know how to check if a button is pressed but is there a better way to call a function instead of looping and checking and making a own listener system? If no, can someone please give me a example to a listener system.

**Comment by Harmless05** [comment]
I think it only works for disabled controls. (Don't quote me on that) I think that it can be used with this control: IS_CONTROL_ENABLED

**Comment by pierrelasse** [comment]
So, i made a key listener myself (actually working) that only triggeres on keydown.
For now i only have keydown and not keyup and only one callback but i can update it if someone wants it.

Edit: For licensingn stuff, you are allowed to use, modify, and distribute the edited and unedited code with crediting me plzplz within that code you are distributing. Translated: plz credit me somewhere ok nice:)
```lua
-- Made by pierrelasse <:D
keyListener = { -- You can make it local
    -- Initializes the system. Only call once
    init = function()
        if keyListener.keys ~= nil then
            return nil
        end
        keyListener.keys = {
            ["ESC"] = 322, ["F1"] = 288, ["F2"] = 289, ["F3"] = 170, ["F5"] = 166, ["F6"] = 167, ["F7"] = 168, ["F8"] = 169, ["F9"] = 56, ["F10"] = 57,
            ["~"] = 243, ["1"] = 157, ["2"] = 158, ["3"] = 160, ["4"] = 164, ["5"] = 165, ["6"] = 159, ["7"] = 161, ["8"] = 162, ["9"] = 163,
            ["-"] = 84, ["="] = 83, ["BACKSPACE"] = 177, ["TAB"] = 37, ["Q"] = 44, ["W"] = 32, ["E"] = 38, ["R"] = 45, ["T"] = 245, ["Y"] = 246,
            ["U"] = 303, ["P"] = 199, ["["] = 39, ["]"] = 40, ["CAPS"] = 137, ["A"] = 34, ["S"] = 8, ["D"] = 9, ["F"] = 23, ["G"] = 47, ["H"] = 74,
            ["K"] = 311, ["L"] = 182, ["LEFTSHIFT"] = 21, ["Z"] = 20, ["X"] = 73, ["C"] = 26, ["V"] = 0, ["B"] = 29, ["N"] = 249, ["M"] = 244,
            [","] = 82, ["."] = 81, ["LEFTCTRL"] = 36, ["LEFTALT"] = 19, ["SPACE"] = 22, ["RCTRL"] = 70, ["D"] = 178, ["D"] = 173, ["HOME"] = 213,
            ["PAGEUP"] = 10, ["PAGEDOWN"] = 11, ["DEL"] = 178, ["R"] = 70, ["R"] = 175, ["H"] = 213, ["LEFT"] = 174, ["RIGHT"] = 175, ["TOP"] = 27,
            ["DOWN"] = 173, ["T"] = 37, ["T"] = 27, ["N4"] = 108, ["N5"] = 60, ["N6"] = 107, ["N+"] = 96, ["N-"] = 97, ["N7"] = 117, ["N8"] = 61,
            ["N9"] = 118, ["MOUSE2"] = 25, ["MOUSE1"] = 24, ["INSERT"] = 121
        }
        keyListener.cb = {}
        keyListener.ks = {}
    end,
    -- Needs to be executed as much as possible or what makes sense
    tick = function()
        if keyListener.keys == nil then
            return nil
        end
        for k, _ in pairs(keyListener.cb) do
            if PAD.IS_DISABLED_CONTROL_PRESSED(0, k) then
                if keyListener.ks[k] == nil then
                    keyListener.ks[k] = true
                    if keyListener.cb[k] then
                        keyListener.cb[k]()
                    end
                end
            else
                keyListener.ks[k] = nil
            end
        end
    end,
    -- Sets a callback for a key
    set = function(key, callback)
        if keyListener.keys == nil or key == nil or callback == nil then
            return nil
        end
        keyListener.cb[key] = callback
    end,
    -- Removes the set callback for a key
    unset = function(key)
        if keyListener.keys == nil or key == nil then
            return nil
        end
        keyListener.cb[key] = nil
    end
}

-- Usage
keyListener.init() -- Initialize the system

keyListener.set(keyListener.keys["L"], function() -- Register a listener
    log.info("Key L was pressed!")
end)

script.register_looped("keylistener", function() -- Register a loop
    keyListener.tick()
end)
```

**Comment by Harmless05** [comment]
@pierrelasse Can I modify the script and add it to my Lua repo list? I will credit it you ofc

**Comment by pierrelasse** [comment]
yes np @Harmless05
