### ISSUE TITLE
[Improvement]: Consistency between Vehicle spawn tabs

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2048]
### Which feature

The New and Personal Vehicle tabs have an option to preview the vehicle and determine if you want to be teleported into the vehicle, as well as New having Spawn Max and Personal having Spawn Cloned, but those are specific to those features. With the recent introduction of #2042, I feel each vehicle box should conform to the same standard. No more than 30 items per box, and we at least show Preview and Spawn In checkboxes for both the XML and the Persist tab. The Personal vehicle tab also shows vehicles that should not be spawned as personal vehicles, such as the Avenger, acid lab bike, Terrorbyte, and others like the RC Bandito and the Invade and Persuade tank. We should only show them if Spawn Clone is checked, as we could potentially get the user flagged by Rockstar if they assign their personal vehicle slot to a vehicle that can't normally be a personal vehicle. 

### Reason

Consistency.

**Comment by lonelybud** [comment]
> The Personal vehicle tab also shows vehicles that should not be spawned as personal vehicles, such as the Avenger, acid lab bike, Terrorbyte, and others like the RC Bandito and the Invade and Persuade tank. We should only show them if Spawn Clone is checked, as we could potentially get the user flagged by Rockstar if they assign their personal vehicle slot to a vehicle that can't normally be a personal vehicle.

Was this change done as I can see still avenger in personal vehicle when clone is not checked.

![image](https://github.com/YimMenu/YimMenu/assets/139460769/d3f69c9e-bf02-4a57-9732-017e2654717f)

**Comment by gir489returns** [comment]
>Was this change done as I can see still avenger in personal vehicle when spawn clone is not checked.

I forgot that. Reopening the issue.
