### ISSUE TITLE
[Request]: Request data from site in scripts

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2069]
### Problem

I want to make auto update for script how it is often used bobox (roblox) scripts.

### Solution

Add a function that inputs an url and returns the response for that url.

### Reason

See problem

### Additional context

I know this is meh because autoupdate and so meh.
Maybe someone has a better idea but idk if you want to make your script and first copy paste some big chunky code above your script before you can start.

**Comment by gir489returns** [comment]
This is a stupid request.

**Comment by FIying-Scotsman** [comment]
I would be cautious against this from a security perspective. Even though Yimmenu stops most abusable Lua APIs (like running system commands etc), it still could be open to users updating their scripts at random with malicious code (i.e running detected transactions on your account as soon as the script loads) and you wouldn't be any the wiser given the script is auto-updating and to you, still working fine.

At least having to manually copy updates over - you've got a chance to spot malicious bits of code or at minimum someone will likely be affected before you update and would warn everyone (which isn't possible if everyone auto-updates at the same time).

**Comment by pierrelasse** [comment]
Okay then is it possible to "require" scripts in another script? So it loads script a and everything from script a, i can use in script b where i "required" it.

**Comment by pierrelasse** [comment]
> This is a stupid request.

What a helpful comment

**Comment by xiaoxiao921** [comment]
> Okay then is it possible to "require" scripts in another script? So it loads script a and everything from script a, i can use in script b where i "required" it.

Lua require is already supported. And I agree with Flying-Scotsman. Self updating scripts is too risky for security I'm afraid

**Comment by pierrelasse** [comment]
Then how do i do it?

**Comment by xiaoxiao921** [comment]
[Check the "basic self library" section](https://github.com/YimMenu/YimMenu/discussions/1389#discussioncomment-6156344)
