### ISSUE TITLE
[Request]: Search name by rockstart id

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2072]
### Solution

Add the ability to search for the name with a rid in Network -> Player Database.

### Reason

Because why not?

**Comment by WorthIessPricetag** [comment]
![pdb](https://github.com/YimMenu/YimMenu/assets/140771500/a35a3e7d-2176-41fc-bbf0-b79e4d496535)

**Comment by pierrelasse** [comment]
Cool that you found out how to make screenshots

**Comment by WorthIessPricetag** [comment]
I also added the red triangle, in case you missed. :)  
You can paste any RID there and you will get the name connected to it.

**Comment by pierrelasse** [comment]
Oh ok then
