### ISSUE TITLE
[Request]: ImGui to List UI

### ISSUE THREAD

**Issue by Vlhss** [YimMenu/YimMenu#2084]
### Problem

Be able to switch from ImGui to List (native) UI just like Luna did before it shut down. Basically just have a toggle under the Settings submenu that when enabled it will switch to List UI and vise versa. It will obviously only be navigable with a controller and not a mouse

### Solution

-

### Reason

-

### Additional context

-

**Comment by Tayipc38** [comment]
With a project of this size and the sheer amount of UI elements already deployed, a conversion for an alternative GUI would require a hefty amount of work. It may not be difficult, but it sounds like hard labor. I don't think this will be made so I advise closing this issue as "will not do".

**Comment by Vlhss** [comment]
> Why? Because you like it? If you like it so much then paste in a native menu. ImGui is superior, there is 0 reasons to implement a native menu over ImGui.

chill the fuck out was just a suggestion, acting like you will implement it
