### ISSUE TITLE
[Questsion/Request]: Anti transaction rate limit

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2102]
### Problem

So, i found a guard sleeping and looted him after joining a random session.
When it was "done" the console was spammed with "Received transaction rate limit".
This was legit so no random event was forced etc.

Now my question is, can you get banned, get flagged or get sussed out for this?
Or is this completely fine and no one cares?
I know that the ppl here are not working at rockstar but maybe someone knows it.

### Solution

So my feature request would be that it would cancel all transaction requests so it only i only receive transaction rate limit once and not multiple times.
This would (maybe) not get you sussed out too much? Idk

### Reason

Why does this field exist...

### Additional context

Would be good maybe to not get banned if it is bad to receive transation rate limit but optional.
And stfu if you want me to tell that this is bloat for the menu and unneeded. You can leave this thing called reaction on this post

**Comment by alyxme** [comment]
"Received transaction rate limit" descibed itself. Each time when you receive GTA$, variables is incremented in certain Global_* value. When rate limit is exceeded, the flag of "high earner" may be applyed to your account by RAC script and may result to ban penalty. Depends on how much often it triggered. First or two warnings you may ignore as probably safe.  
<details><summary>for example</summary>
<p>

```
(int)MPPLY_CASINO_CHIPS_PUR_GD //Casino chips the player has purchased from the house shop this past gameday 
(int)MPPLY_CASINO_CHIPS_PURTIM //Time of purchase for casino chips from the house 
(int)MPPLY_CASINO_CHIPS_WON_GD //Casino chips the player has won by betting this past gameday 
(int)MPPLY_CASINO_CHIPS_WONTIM //Time of winning a bet against the house 
```

</p>
</details> 

I dont think this request will come into mastercode ever but it is possible to mess with LUA.

**Comment by pierrelasse** [comment]
Hm okay. Thanks

**Comment by Yimura** [comment]
Whatever you did probably queued a lot of transactions of the same type.
As a solution you can just disable that log from appearing by toggling it under Settings > Reactions > Transaction Ratelimit or try to not do whatever you where doing. The menu should normally automatically dismiss the popup for the transaction warning but if you manage to keep triggering it by looping a certain transaction it'll keep getting triggered.
This is not a bug with the menu or something we can fix as that transaction popup should only appear if you're sending to many transactions to R*'s servers (aka. it's fully server-sided and we can't change that behaviour).


Relevant code:
https://github.com/YimMenu/YimMenu/blob/29fdb5c3bca874ff01f1c7cd97c570541120d1f3/src/native_hooks/shop_controller.hpp#L9-L24
