### ISSUE TITLE
[Bug]: Crash when reloading scripts

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2150]
### Describe the bug

Reload all scripts but before delete a the target script or entire script folder

### Steps To Reproduce

See above

### Expected Behavior

No crash and it unloads

### Logs and/or screenshots

Too long to put here

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
We'll merge this with #2151.
