### ISSUE TITLE
[Request]: Instant storymode? (QOL)

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2157]
### Problem

I have to waste so much time when kicked from a session or whatever to join storymode before being able to do anything.

### Solution

So is there a way (in theroy yes) to go in a version of storymode without any features so im instantly / superfast in there?

### Reason

See problem

### Additional context

QOL

**Comment by tupoy-ya** [comment]
We can hook `ON_ENTER_SP` native so you don't load single player map when leaving online.

This speeds up single player loading by a lot for me, would be less effective if the game is installed on an SSD.
```cpp
add_native_detour(RAGE_JOAAT("maintransition"), 0xD7C10C4A637992C9, maintransition::ON_ENTER_SP); // Prevent single player map from loading when going back from online.


/**
 * @brief Prevent single player map from loading when going back from online.
 */
inline void ON_ENTER_SP(rage::scrNativeCallContext* src)
{
	if(!g.tunables.dont_unload_online_maps)
		DLC::ON_ENTER_SP();
}
```

**Comment by gir489returns** [comment]
@tupoy-ya Could this flow the other direction? If you were in SP and load MP, could you prevent it from loading the map again?

**Comment by tupoy-ya** [comment]
> @tupoy-ya Could this flow the other direction? If you were in SP and load MP, could you prevent it from loading the map again?

If you mean preventing online map from loading then you can prevent it, but if you spawn in an interior then you will get an infinite loading if i remember correctly, could be wrong don't test this in a while.

EDIT:
If you skipped `ON_ENTER_SP` when entering single player then the game will not load online map again when going back into MP because it is already loaded.

**Comment by gir489returns** [comment]
Then how would that work the other way? If you were in the casino and load into SP, you'd get an infinite load too?

**Comment by tupoy-ya** [comment]
> Then how would that work the other way? If you were in the casino and load into SP, you'd get an infinite load too?

No, it will start single player scripts and you will just spawn in Michael's house for example.

**Comment by pierrelasse** [comment]
Isee there is no easy way to go in some sort of limbo state map....

**Comment by tupoy-ya** [comment]
> I see there is no easy way to go in some sort of limbo state map....

You can probably do it (not easy), but it will save you about 20 seconds, while you can save 10 seconds by just calling `STREAMING::STOP_PLAYER_SWITCH();`.

I personally don't see a point in this because single player start really fast,
the longest part is the map loading(The `ON_ENTER_SP` one) and the map loading(The sky cam(player switch) one).

**Comment by pierrelasse** [comment]
> > I see there is no easy way to go in some sort of limbo state map....
> 
> You can probably do it (not easy), but it will save you about 20 seconds, while you can save 10 seconds by just calling `STREAMING::STOP_PLAYER_SWITCH();`.
> 
> I personally don't see a point in this because single player start really fast, the longest part is the map loading(The `ON_ENTER_SP` one) and the map loading(The sky cam(player switch) one).

Ok so this just removes me from the clouds but i can't do anything else then freecam around.
I saw that stand had a feature where when joining you could already do stuff and move around while joining. Do you maybe know how to achive this? This would be a cool feature for Network->Fast Join

Edit: I probably meant to skip "Ending session" or "Shutting down session" instead of making singleplayer faster to load.

**Comment by tupoy-ya** [comment]
> Ok so this just removes me from the clouds but i can't do anything else then freecam around.

I use it to skip zooming in from the clouds animation when going from MP to SP.
Maybe some of the seamless join hooks are making it work.

> I saw that stand had a feature where when joining you could already do stuff and move around while joining. Do you maybe know how to achieve this? This would be a cool feature for Network->Fast Join

See #1529

> Edit: I probably meant to skip "Quitting session" or "Shutting down session" instead of making singleplayer faster to load.

It should be possible, but the easy way i see of doing it would not clean up the multi player stuff after itself.

A theory that i didn't test:
```cpp
// maintransition
int func_1920(var uParam0) // Hash - 0x65B95DBC
// Path func_1435 /* Hash - 0x939550B0 */ to return false in this function and it should skip the switch.
```
Again i don't see a point in doing it - Single Player loading is already fast, or maybe it's not i only played GTA Online once in the last 2 months.

**Comment by pierrelasse** [comment]
> Edit: I probably meant to skip "Ending session" or "Shutting down session" instead of making singleplayer faster to load.

**Comment by pierrelasse** [comment]
> > Ok so this just removes me from the clouds but i can't do anything else then freecam around.
> 
> I use it to skip zooming in from the clouds animation when going from MP to SP. Maybe some of the seamless join hooks are making it work.
> 
> > I saw that stand had a feature where when joining you could already do stuff and move around while joining. Do you maybe know how to achieve this? This would be a cool feature for Network->Fast Join
> 
> See #1529
> 
> > Edit: I probably meant to skip "Quitting session" or "Shutting down session" instead of making singleplayer faster to load.
> 
> It should be possible, but the easy way i see of doing it would not clean up the multi player stuff after itself.
> 
> A theory that i didn't test:
> 
> ```c++
> // maintransition
> int func_1920(var uParam0) // Hash - 0x65B95DBC
> // Path func_1435 /* Hash - 0x939550B0 */ to return false in this function and it should skip the switch.
> ```
> 
> Again i don't see a point in doing it - Single Player loading is already fast, or maybe it's not i only played GTA Online once in the last 2 months.

Hm okay
