### ISSUE TITLE
[Bug]: Godmode fails to protect you against events that subtract health.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2164]
### Describe the bug

When doing certain actions, the player can have their health subtracted, even with godmode. The most common way I know how to reproduce this bug is by smoking cigarettes. 

### Steps To Reproduce

1. Do the LSD supply run until you find the one with the chemical spill.
2. Go inside the chemical spill.
3. Take damage.

### Expected Behavior

Should be protected from all forms of damage.

### Store

Rockstar

### Additional context

![image](https://github.com/YimMenu/YimMenu/assets/100792176/6ccdbe09-3342-4e46-874e-73551bd8cd52)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by pierrelasse** [comment]
There should be a semi godmode too in the self tab

**Comment by gir489returns** [comment]
Reopening as the mission and behavior this bug was opened for still occurs.

**Comment by yousef157** [comment]
> ### Additional context
> 
> ![image](https://user-images.githubusercontent.com/100792176/269129720-6ccdbe09-3342-4e46-874e-73551bd8cd52.png)

sorry for the off-topic question, but how exactly did you achieve custom wasted text in online?

**Comment by Yimura** [comment]
By hooking the function that goes from the text label to the appropriate translation text:
https://github.com/YimMenu/YimMenu/blob/3b714f5c67d57c75de532ee17df17d01633cf83a/src/services/custom_text/custom_text_service.cpp#L9
https://github.com/YimMenu/YimMenu/blob/3b714f5c67d57c75de532ee17df17d01633cf83a/src/services/custom_text/custom_text_callbacks.cpp#L5-L11

**Comment by yousef157** [comment]
Oh, I see, that text was already in the code. I assume there is already a custom wanted text box in the menu? I can't really check right now
