### ISSUE TITLE
[Request]: Disable someones passive mode

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2176]
### Problem

Sometimes ppl go in pussy mode.

### Solution

Make it so you can disable the passive mode of a player :D

### Reason

Plz remove this field

### Additional context

Would be cool. I think it does that when you give someone a bounty through lester.

**Comment by Yimura** [comment]
It’s not possible to disable someone’s passive mode only to lock them from changing their passive mode which we will definitely not add to YimMenu.

**Comment by pierrelasse** [comment]
Uh ok

**Comment by gir489returns** [comment]
You can still kill them with the damage function that Yim calls to kill NPCs. If you make it think the damage is coming from them, they keep suiciding.
