### ISSUE TITLE
[Bug]: GUI_TAB_PLAYER not working

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2184]
### Describe the bug

This is the code in my script
```lua
gui.get_tab("GUI_TAB_PLAYER"):add_text("Hmh")
```

and instead of gui.get_tab returning the player "tab", it makes a new tab.

![image](https://github.com/YimMenu/YimMenu/assets/76223390/156020cb-6379-4879-b8da-200a205ce099)

### Steps To Reproduce

Make a script with this code:
```lua
gui.get_tab("GUI_TAB_PLAYER"):add_text("Hmh")
```

### Expected Behavior

gui.get_tab returns the correct tab

### Store

Other (please mention in "Additional context")

### Additional context

AmogusStore

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
`GUI_TAB_PLAYER` does not exist at runtime, thats why it is creating new one. 

edit: you can look at the list of available tabs by searching "GUI_TAB_" in https://github.com/YimMenu/Translations/blob/master/en_US.json

**Comment by gir489returns** [comment]
> `GUI_TAB_PLAYER` does not exist at runtime, thats why it is creating new one.

https://github.com/YimMenu/YimMenu/blob/715af5203e08da9326a6eab0fdd89ca0d5b55838/docs/lua/tabs.md?plain=1#L59

Documentation says otherwise. Regardless, we have to fix [something ](https://github.com/YimMenu/YimMenu/blob/715af5203e08da9326a6eab0fdd89ca0d5b55838/src/services/gui/gui_service.hpp#L162) in the code, and I guarantee you nobody cares enough on our end to do it.

**Comment by pierrelasse** [comment]
I want to add stuff to the player entry. So there is  urrently no way of doing this and the docs say it is possbiel but no one wants to code it. Isee

**Comment by xiaoxiao921** [comment]
The player tab is not declared like the others like gir pointed out, this is why you can't add to it currently.

**Comment by Yimura** [comment]
Previously it was possible to do, was there a regression made?

**Comment by xiaoxiao921** [comment]
I don't recall this ever being possible, but  I could be wrong

**Comment by Yimura** [comment]
```lua
RANK_INPUT = gui.get_tab(""):add_input_int("Rank")
```

This is very old code from the initial version of when Lua was first implemented, I'm not sure it still works today as I had to go through my trashbin to find it.

**Comment by pierrelasse** [comment]
> ```lua
> ```lua
> RANK_INPUT = gui.get_tab(""):add_input_int("Rank")
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> This is very old code from the initial version of when Lua was first implemented, I'm not sure it still works today as I had to go through my trashbin to find it.
> ```

Bruh how full is your trashbin if you still have this.
Is there anyone that could test this?

**Comment by xiaoxiao921** [comment]
> ```lua
> RANK_INPUT = gui.get_tab(""):add_input_int("Rank")
> ```
> 
> This is very old code from the initial version of when Lua was first implemented, I'm not sure it still works today as I had to go through my trashbin to find it.

This should work, it's just that "" doesn't make sense really for the player tab

**Comment by lonelybud** [comment]
try this -

src/services/gui/gui_service.hpp

```C++
		        {"Player", view::view_player},
```
src/views/core/view_navigation.cpp

```c++
				// case tabs::PLAYER:
				// case tabs::DEBUG: continue;
```

initially -
![image](https://github.com/YimMenu/YimMenu/assets/139460769/c19ce8e1-e378-405b-af60-14c386b51fa2)
after clicking on a player -
![image](https://github.com/YimMenu/YimMenu/assets/139460769/f5f9aa36-5d23-4409-981b-dd2bf9d88b66)
