### ISSUE TITLE
[Request]: Someone killing in your name detection

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2204]
### Problem

Some modders spawn explosion on all players and if they die, it tells that you killed them in the "chat".

### Solution

Make a detection like `SomeFatKid killed SomePlayer in your name` or whatever

### Reason

dwdwdwdwdw

**Comment by Yimura** [comment]
We have this sort of detection implemented in the menu but it’s really hard to implement correctly.

**Comment by pierrelasse** [comment]
Hmm okay. Should i close this?
