### ISSUE TITLE
[Improvement]: network.flag_player_as_modder should have reason arg

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2209]
### Which feature

There is this in lua api thingy and you can only flag a player but you can't add a reason to it which is not good:
### `flag_player_as_modder(player_idx)`

Flags the given player as a modder in our local database.

- **Parameters:**
  - `player_idx` (integer): Index of the player.

**Example Usage:**
```lua
network.flag_player_as_modder(player_idx)
```

### Reason

Solution: Add the following thing

### `flag_player_as_modder(player_idx, reason)`

Flags the given player as a modder in our local database.

- **Parameters:**
  - `player_idx` (integer): Index of the player.
  - `reason` (string): Uhhhhhhhhhhh.

**Example Usage:**
```lua
network.flag_player_as_modder(player_idx, "Too fat to handle")
```

**Comment by pierrelasse** [comment]
Closed due to https://github.com/YimMenu/YimMenu/pull/2248

**Comment by xiaoxiao921** [comment]
That's not how it work, as long as the PR is not merged you don't close the associated issue.

**Comment by pierrelasse** [comment]
Okay sorry. I thought chatting should continue there.
