### ISSUE TITLE
[Improvement]: ImGui.Selectable being weird (low prio)

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2219]
### Which feature

Currently not important but still kinda annoying.
So when i use ImGui.Selectable
Example
```
if ImGui.Selectable("Abc", false) then
  log.info("I was clicked!")
end
```

'I was clicked' will get printed when the selectable is clicked.
But when i change the second arg to true (which is the selected state), it spams 'I was clicked' the entire time even tho it was not clicked. I don't know if this is the intended way for the feature. But if so, this is not nice to use and i would like to have the returned value act the same as when arg2 is false.

### Reason

dawgwehghgwehh

### Additional context

whehwehehwg

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/blob/master/docs/lua/tables/ImGui.md#widgets-selectables

Classic case of user stupidity.

**Comment by pierrelasse** [comment]
Yes cool that's the usage? It returns true when selected is true and it returns true when it was clicked and selected is false? What is there stupid?

**Comment by gir489returns** [comment]
You're passing it an immutable value.

**Comment by pierrelasse** [comment]
Ik.

Is there a way to create a mutable var? This would make things soooo much easier.

**Comment by gir489returns** [comment]
local selected = false then pass selected?

**Comment by pierrelasse** [comment]
I meant like (similar to &var in c++)

asdf = true

function somefunc(a)
  a = false
end

somefunc(asdf)

print(asdf) prints false
