### ISSUE TITLE
[Bug]: ImGui.GetStyle access

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2221]
### Describe the bug

So i saw that GetStyle is in the lua api but the function was not set.
```c++
inline ImGuiStyle& GetStyle()
{
	return ImGui::GetStyle();
}
```
But it was not set unlike other functions.
```c++
ImGui.set_function("GetStyle", GetStyle); // This is missing
```

### Steps To Reproduce

local success = type(ImGui.GetStyle) == "function" -- Will be false

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
https://github.com/YimMenu/YimMenu/blob/207e5457f9fca9e638168b1f26ec210116d7ad7d/src/lua/bindings/imgui.hpp#L3587

**Comment by pierrelasse** [comment]
Hell nah
