### ISSUE TITLE
[Request]: Expose cache to lua

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2240]
### Problem

I don't want to make my code messy and fill with useless things.

### Solution

Add (or smth like that)

cache.get_all_weapons() : {weaponName = weaponHash}
cache.get_all_vehicles() : {vehicleName = vehicleHash}

and so on for objects, peds, weapon attachments?, and whatever is cached

### Reason

Would be really cool and would make the code much cleaner and why not use something that already exists?

**Comment by Tayipc38** [comment]
> Would be really cool and would make the code much cleaner and why not use something that does not already exist?

Do you even read back what u wrote?

**Comment by pierrelasse** [comment]
> > Would be really cool and would make the code much cleaner and why not use something that does not already exist?
> 
> Do you even read back what u wrote?

No

**Comment by CypherMorgan** [comment]
> > Would be really cool and would make the code much cleaner and why not use something that does not already exist?
> 
> Do you even read back what u wrote?

My Brain.exe stopped responding after reading the request haha (Sorry, off-topic)

**Comment by pierrelasse** [comment]
> > > Would be really cool and would make the code much cleaner and why not use something that does not already exist?
> > 
> > 
> > Do you even read back what u wrote?
> 
> My Brain.exe stopped responding after reading the request haha (Sorry, off-topic)

I stopped reading back my things here bec there is a high chance one off these things happening
- no answer
- offtopic
- saying why not to implement the feature
- saying that no ine is making this feature cuz too lazy
- offtopic, complaining about things and saying not why
- writing own version of bible
- other

**Comment by xiaoxiao921** [comment]
You see I thought that request was pretty valid but you always manage to annoy and piss off contributors working on this because of your fucking awful attitude. Like every open source projects feel free to contribute yourself and do the pr. We don't have to give any reason you would deem valid for doing or not doing something because we do this as a hobby and we are not the slaves of a random we don't even know talking to us through GitHub issues. Now if you could stop with the off topics comment every now and then before you get banned from posting in this repo totally.

**Comment by pierrelasse** [comment]
i just answered that dude and dint want to attack anyone and i never said that anyone is doing anything bad or not enough.
now this is again going offtopic and is a new bible.

**Comment by gir489returns** [comment]
I agree with xiao, you've become just like that freeman asshole, you're demanding, repetitive and really fucking annoying.

**Comment by pierrelasse** [comment]
wtf where did i demand anything?
where did i do something like @xyz do this or do that?

**Comment by xiaoxiao921** [comment]
> i just answered that dude and dint want to attack anyone and i never said that anyone is doing anything bad or not enough. now this is again going offtopic and is a new bible.

?

In your previous message you said that you didn't even bother reading the comments of the threads you create (basically the equivalent of spamming if you don't even care about the answer/feedback we give) because we, the contributors that write the code that you ask for, are giving reasons on why or why not we will do it, do you realize how much of a dick you are when you write this?

**Comment by pierrelasse** [comment]
> > i just answered that dude and dint want to attack anyone and i never said that anyone is doing anything bad or not enough. now this is again going offtopic and is a new bible.
> 
> ?
> 
> In your previous message you said that you didn't even bother reading the comments of the threads you create (basically the equivalent of spamming if you don't even care about the answer/feedback we give) because we, the contributors that write the code that you ask for, are giving reasons on why or why not we will do it, do you realize how much of a dick you are when you write this?

i said that i dont bother reading back my texts too much for spekling mistakes because no one cares if anyone even sees it.
and im really happy about feedback because other people maybe have a good idea too which could make the SUGGESTED feature even better.
why would i spend my time arguing here and making issues if i dint care about the menu/project? i „love“ it and im really thankful for everyine who contributed and i never demand something.
and that you are maybe picking things up wrongly/not how i meant it is not good because i care obv about the ppl and the project. if iwouldnt care i would just i guess not do anything here?
i even did translations. what person does not care about something yet makes a pull request and has a public repo where amscript is that devs can use to easier develop scripts…

**Comment by xiaoxiao921** [comment]
We are reading you though, why should we put effort on even bothering reading what you are asking if you don't put any effort yourself?

**Comment by KLXYinc** [comment]
> Author

i've seen that happening here quite alot.
