### ISSUE TITLE
Auto-Kick Spam Bots

### ISSUE THREAD

**Issue by OXKSA1** [YimMenu/YimMenu#228]
**Is your feature request related to a problem? Please describe.**
its not

**Describe the solution you'd like**
automatically kick bots thats spam 20 chat messages and phone text in 1 seconds

**Provide Reasoning**
nearly every game i enter there is some bots who spam me

**Additional context**
something like this may help:

https://github.com/HolyWurl/Block-GTASpamMessage

**Comment by xM4ddy** [comment]
Relevant: https://www.unknowncheats.me/forum/grand-theft-auto-v/493539-dealing-chat-spammers.html

**Comment by Tayipc38** [comment]
> Relevant: https://www.unknowncheats.me/forum/grand-theft-auto-v/493539-dealing-chat-spammers.html

As useful as this was, its now obsolete. I can conjure the same method with exponential effectiveness via the netmsg receiver @maybegreat48 blessed us with.
