### ISSUE TITLE
[Request]: Access to cache in lua scripts

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2299]
### Problem

I want to access the cache in my lua script.

### Solution

Add something like `cache.get_all_weapons()` which would return a table for example like this:
```lua
{
  ["WEAPON_ADVANCEDRIFLE"] = 2937143193
}
```

### Reason

So i don't have to paste long things into my script

**Comment by erm999** [comment]
Hi there,
Sorry this isn't related, but I wasn't sure how to contact.
I was wondering if there's a guide on how to use the HBO feature 
on SussySpt and if all features are working. 
Thanks

**Comment by pierrelasse** [comment]
> Hi there, Sorry this isn't related, but I wasn't sure how to contact. I was wondering if there's a guide on how to use the HBO feature on SussySpt and if all features are working. Thanks

My discord is: dcistdreck
