### ISSUE TITLE
[Improvement]: See error when 'Exception caught while trying to call ??? native.'

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2308]
### Which feature

See title

### Reason

ENTITY.DOES_ENTITY_EXIST throws super often errors and i'm not able to fix it.
I don't know if it's possible to get a somewhat useful error, but i don't think.
It would also help if there's an good alternative to ENTITY.DOES_ENTITY_EXIST.

Edit: Does pcall catch the error? Probably not right?

**Comment by lonelybud** [comment]
run in fiber. Also ensure that your code does not execute on unkown value

**Comment by pierrelasse** [comment]
> run in fiber. Also ensure that your code does not execute on unkown value

Edit: I fixed the code, but the question still persists if it's possible to see a somewhat helpful error.

**Comment by lonelybud** [comment]
> > run in fiber. Also ensure that your code does not execute on unkown value
> 
> Edit: I fixed the code, but the question still persists if it's possible to see a somewhat helpful error.

you mean the  hexadecimal number you see in `Exception caught while trying to call ???` should log actual function that is failing?

**Comment by pierrelasse** [comment]
> > > run in fiber. Also ensure that your code does not execute on unkown value
> > 
> > 
> > Edit: I fixed the code, but the question still persists if it's possible to see a somewhat helpful error.
> 
> you mean the hexadecimal number you see in `Exception caught while trying to call ???` should log actual function that is failing?

Nah, i can just look up the function in a natives list.
It is probably very hard to do but it would be cool if you see where in your script the functikn made an error or the errors stacktrace but i dont think thats easy to do.

You could also technically automatically translate the hex to the real function nae and maybe wih what args it was called too.
This would probably make it easier to debug.

**Comment by Yimura** [comment]
Making a list of all the natives would require us to embed a string of each native in the game combined with its hash. This will bloat the binary even more than it currently is.

**Comment by pierrelasse** [comment]
I know and you just look it up in a natives list to figure out what bative caused the issue and then try figuring out where in your code the error occured
