### ISSUE TITLE
[Improvement]: cancel @gir

### ISSUE THREAD

**Issue by 7HA7MA77** [YimMenu/YimMenu#2363]
### Which feature

@gir489returns 
he's closing my issues proposition threads and then releasing updates cointaining that content (but made worse than i proposed, way worse, as holdshift is way smarter to delete than spam with "X"'s), it's rly pathetic, @Yimura can you cancel his github perimsions to taking down the issues? THanksie, cheers.

### Reason

some ppl just need to grow up

**Comment by 7HA7MA77** [comment]
https://github.com/YimMenu/YimMenu/issues/2358

**Comment by 7HA7MA77** [comment]
5 good propositions closed by him, one stolen and instead of made goodway of deleting, like teleports, shift to delete - he spamemd gui with nooblooking "X" (that X buttons arent visible if name is too long... gir, you kiddo.. lol)

**Comment by 7HA7MA77** [comment]
@gir489returns closed my thread with message "sethe harded fargot" ... 
and after that he duplicated my idea and made as "hey guys i made great improvement" xDDDDDDDDDDDDDDDDD
https://github.com/YimMenu/YimMenu/issues/2352

**Comment by gir489returns** [comment]
Seethe harder, again, faggot.
