### ISSUE TITLE
[Request]: Fix gta online cutscene

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2374]
### Problem

So i don't know it it's already fixed tho i got sent in the long gta cutscene while playing. My friend also got the cutscene by a modder yesterday.

### Solution

Add a button to skip or prevent it in the first place.

**Comment by gir489returns** [comment]
https://github.com/YimMenu/YimMenu/blob/d277f1660d239507b8ce926025056fe53ae0f4dc/src/backend/commands/self/skip_cutscene.cpp#L16

Can you at least look at the code before making tickets?

**Comment by pierrelasse** [comment]
Can you atleast look at the request before closing the issue?
![image](https://github.com/YimMenu/YimMenu/assets/76223390/14a68505-c04f-4903-bd66-1f256d8be88f)
"unskippable"

**Comment by Yimura** [comment]
To be fair there was a bit of information missing from your issue, it didn't mention any specific cut scene.

**Comment by pierrelasse** [comment]
Yeah sorry i didn't tell it clear enough. "long gta cutscene" :/
Could you maybe reopen this please.
