### ISSUE TITLE
[Improvement]: add language input criteria for future tickets

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2381]
### Which feature

Add a language selection to each bug report similar to how we ask which store they got GTA V in. 

### Reason

#2377 exposed a glaring issue with issue reproduction

### Additional context

We may also want to collect the game’s language they use too.

**Comment by pierrelasse** [comment]
I think it would be better to make a new template because i dont think that the language is needed in most bug reports.

**Comment by Yimura** [comment]
@pierrelasse, I think you might be misunderstanding. Some bugs can only be reproduced with certain languages as such this is helpful information to include in bug reports.

**Comment by pierrelasse** [comment]
Oh okay. Tho how can some diffrent strings can break something or am i missing something?

**Comment by Yimura** [comment]
It's usually because of a mismatch in formatting in the strings, you know how some strings have numbers in them that dynamically change.
Well if those formats are incorrectly used or not present in the string at all it may cause a crash.
