### ISSUE TITLE
[Bug]: With Yimmenu, the game crashes frequently, and there are no error logs

### ISSUE THREAD

**Issue by iwanttodo1t** [YimMenu/YimMenu#2400]
### Describe the bug

It wasn't a crash caused by what feature was used, but a crash without warning, no error logs, I don't know if it was a bug or another cheater that crashed my game

### Steps To Reproduce

.

### Expected Behavior

.

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by yousef157** [comment]
Logs?

**Comment by Rabtos** [comment]
It worked fine for me. There is a new build anyway now. So try dat one..

**Comment by yousef157** [comment]
No error logs? If so, what injector are you using? Also, does this happen if you go into invite only sessions for a while?

**Comment by rr1231234** [comment]
try to delete anything related to yimmenu in %APPDATA% folder and then inject it again while playing

**Comment by Yimura** [comment]
@deepdream88 could you confirm this issue is still present, there have been a couple of changes made to the code base in the last month or so that could've changed or fixed this behaviour.
