### ISSUE TITLE
[Request]: Hand-held items

### ISSUE THREAD

**Issue by Asiamies** [YimMenu/YimMenu#2428]
### Problem

One time not too long ago, I saw another modder take out a camera (like the paparazzo in story mode) and start "taking pictures" (the camera even flashed). I was wondering if that functionality could be implemented. 

![image](https://github.com/YimMenu/YimMenu/assets/142546146/9a997025-236f-4158-9449-2131044bfe20)

### Solution

-

### Reason

For the heck of it

**Comment by gir489returns** [comment]
Yeah with a Lua script, we're probably not going to add it to base YimMenu as it's such a stupid and specific feature.

**Comment by pierrelasse** [comment]
It's a prop animation. Maybe you can already find it in the animations list, but i'm not too sure.

This is from dpemotes [link to line](https://github.com/andristum/dpemotes/blob/2dffbc507b7c467f3bfa911e428e00d253833eb5/Client/AnimationList.lua#L1954C4-L1966C7)
```lua
["camera"] = {"amb@world_human_paparazzi@male@base", "base", "Camera", AnimationOptions =
   {
       Prop = 'prop_pap_camera_01',
       PropBone = 28422,
       PropPlacement = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0},
       EmoteLoop = true,
       EmoteMoving = true,
       PtfxAsset = "scr_bike_business",
       PtfxName = "scr_bike_cfid_camera_flash",
       PtfxPlacement = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0},
       PtfxInfo = Config.Languages[Config.MenuLanguage]['camera'],
       PtfxWait = 200,
   }},
```

Would anyone be intrested in me porting [dpemotes](https://github.com/andristum/dpemotes) to yimmenu as a script?
