### ISSUE TITLE
[Bug]: Crash when renaming scripts folder

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2437]
### Describe the bug

See Steps To Reproduce and Excpected Behavior

### Steps To Reproduce

1. Start GTA
2. Inject YimMenu
3. Ensure Auto Reload Scripts is on (atleast i have it on)
4. Rename the `%appdata%/YimMenu/scripts` folder to `scripts_` or whatever
5. Look at the error in the console

### Expected Behavior

No errors
Does the same when a script FILE is deleted or renamed

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13415159/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by yousef157** [comment]
Why would you (or anyone really) rename it in the first place?

**Comment by pierrelasse** [comment]
1. I think that this issue is still a bug and valid
2. I renamed it because i wanted to unload all scripts

**Comment by thehorizon84** [comment]
This is not a valid bug as the source is hardcoded to check for dir/scripts and not dir/scripts_

If you want to rename your scripts folder you have to rename it in the source too, otherwise it will cause issues and crashes as the dll is trying to access, read and write files in place that doesn't exist...

**Comment by pierrelasse** [comment]
> This is not a valid bug as the source is hardcoded to check for dir/scripts and not dir/scripts_
> 
> 
> 
> If you want to rename your scripts folder you have to rename it in the source too, otherwise it will cause issues and crashes as the dll is trying to access, read and write files in place that doesn't exist...

As i stated i wanted to unload all scripts.
So, i renamed the folder. YimMenu is checking for file updates in that folder. Folder doesnt exist. YimMenu sad.

Solution: Check if the fking folder exists and stop telling me stories why not to fix this. Im sure others may want to disable all scripts at one to check if a crash is caused by a script or yim.

**Comment by Yimura** [comment]
> Solution: Check if the fking folder exists and stop telling me stories why not to fix this. Im sure others may want to disable all scripts at one to check if a crash is caused by a script or yim.

When the code references a folder or tries to gets a folder it only checks the first time when creating the object. From then it will assume the folder remains intact for the duration of the inject. The menu just doesn't expect the folder to randomly disappear...

So the code does in fact check if it exists but only initially and will only create the folder initially if it doesn't exist. We're just gonna need to add extra code to check if a user has randomly decided to rename / delete the folder.

**Comment by pierrelasse** [comment]
> So the code does in fact check if it exists but only initially and will only create the folder initially if it doesn't exist. We're just gonna need to add extra code to check if a user has randomly decided to rename / delete the folder.

Ok thanks. So this is indeed a valid issue?
Would it make more sense to create the folder or disable automatic reloading or just skip the checks this time?

**Comment by Yimura** [comment]
> Ok thanks. So this is indeed a valid issue? Would it make more sense to create the folder or disable automatic reloading or just skip the checks this time?

My idea was to make a `disabled/` folder under the `scripts/` folder and any scripts in there won't be loaded by YimMenu. Then from the UI add some buttons to unload and load scripts depending on their position in that folder or not.

**Comment by pierrelasse** [comment]
You could also just add a `.disabled` extension to the file maybe.

**Comment by Yimura** [comment]
> You could also just add a `.disabled` extension to the file maybe.

From a user's point of view adding a .disable extension is a lot harder and sometimes even impossible without toggling the feature to show the extensions in explorer. It's a lot better to just have a directory they can drag scripts to to get them disabled.

**Comment by pierrelasse** [comment]
> From a user's point of view adding a .disable extension is a lot harder and sometimes even impossible without toggling the feature to show the extensions in explorer. It's a lot better to just have a directory they can drag scripts to to get them disabled.

Okay, i just saw that somewhere else. That's why i suggested it.

**Comment by binded-zz** [comment]
i spoke about this a few months ago about adding the ability to add a button into the lua scripts page to enable disable scripts with out having to move and or rename files in the folders yimura thought it was a good idea to do a folder which still sounds good 
basically moving them to a disabled folder and skipping loading them

**Comment by yousef157** [comment]
> i spoke about this a few months ago about adding the ability to add a button into the lua scripts page to enable disable scripts with out having to move and or rename files in the folders yimura thought it was a good idea to do a folder which still sounds good basically moving them to a disabled folder and skipping loading them

Are you simply referring to this? https://github.com/YimMenu/YimMenu/issues/2437#issuecomment-1820585472
