### ISSUE TITLE
[Bug]: Heists are completely unplayable when the menu is injected.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2467]
### Describe the bug

Something the menu is doing is preventing mission syncs at the beginning, middle and end of heists. You have to uninject Yim to actually play the missions, or else you'll most likely get stuck trying to enter your car.

### Steps To Reproduce

Use the cellphone to quickfind a heist.
Begin playing.
Get stuck trying to get into a vehicle.

### Expected Behavior

Should be able to play the heists no issue. Sometimes the bug doesn't happen, sometimes it does. I found that playing 3 heists in a row is enough to cause the bug reliably.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

I tried reverting to commit https://github.com/YimMenu/YimMenu/commit/864e15a0bc107310b980929c7b4abeacf1d0215e and I still have the issue. I remember testing heists with https://github.com/gir489returns/YimMenu/commit/43f2bdffd4f64f9a820fae3e0a9e4448f6e0f2f0 so something between then and the commit I link broke it.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
@maybegreat48 I tried commenting out most of the things in the hooks that I thought would be causing this, but nothing fixed it. Do you have any ideas? It feels like that one time we were blocking the sync for the submarine car, except much worse.

**Comment by D-Borkan** [comment]
I noticed sometimes when the mission is started with friends it's kick me or sometime load infinite black screen.
Did this thing also happen to you ?

**Comment by lonelybud** [comment]
> @lonelybud Can you post your settings.json?

i dont use vanilla yimmenu. Also my custom build only save the important one - 
[settings.json](https://github.com/YimMenu/YimMenu/files/13518910/settings.json)

when i joined the heist every other settings such as godmod was off

**Comment by lonelybud** [comment]
> I noticed sometimes when the mission is started with friends it's kick me or sometime load infinite black screen. Did this thing also happen to you ?

for me it happened when i was not in there session. also i noticed that i was not able to apply keycard properly during cayo perico heist.

**Comment by gir489returns** [comment]
> > @lonelybud Can you post your settings.json?
> 
> i dont use vanilla yimmenu. Also my custom build only save the important one - [settings.json](https://github.com/YimMenu/YimMenu/files/13518910/settings.json)
> 
> when i tried to join the heist via phone jobs every other settings such as godmod was off

Maybegreat suggested my settings were contaminated, and indeed they were, when I removed the settings.json, this behavior goes away, so I have to close this ticket as user error.
