### ISSUE TITLE
[Improvement]: Remove "Couldn't io.open a file called ..." log from Lua API

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2498]
### Which feature

https://github.com/YimMenu/YimMenu/blob/6d64bcd1d7676cca5a5f563fc304ba5786d48cb7/src/lua/lua_module.cpp#L213

### Reason

Remove this please or add a way to check if the file exists (if not already possible).

### Additional context

Introduced in this commit https://github.com/YimMenu/YimMenu/commit/bb5dfd14846f0b17dfedaf13a89a726ce8ae830b

**Comment by Yimura** [comment]
I’d wager to leave it in as the console is for developers anyways. As per #2492 .

Be it Lua devs or YimMenu devs.

**Comment by pierrelasse** [comment]
I get the point tho it seems a bit odd since it already returns nil and other functions also don't print a warning to the console.
Now i need to print a message to the console that the user can ignore this warning.

If u dont want to change it then close the issue.

**Comment by Yimura** [comment]
I'm taking another look at this issue, could you post a simple example of what would trigger this warning?

My assumption is that you're trying to read a config file but it doesn't exist which is causing this error to pop up.
In that case you're correct and we should probably remove it, the nil return value should indicate enough to the Lua developer.

**Comment by gir489returns** [comment]
@Yimura You can test this by using [Casino Pacino](https://github.com/YimMenu-Lua/Casino-Pacino/commits/main/) and changing io.open("CasinoPacino.json", "w") from w to r.

**Comment by Yimura** [comment]
Probably should be removed I guess? They can just check the return value if they got a handle or not.

![image](https://github.com/YimMenu/YimMenu/assets/24669514/5f51fb59-ef50-4e62-91d3-9a89707c91ec)

**Comment by gir489returns** [comment]
Probably. @xiaoxiao921 Do you remember what the original usecase of this message was?

**Comment by xiaoxiao921** [comment]
I think it's good to keep it but only if the dev want to write to the file, thought?

**Comment by gir489returns** [comment]
That's fair. @Yimura What is the requirement for removing it?

**Comment by Yimura** [comment]
> That's fair. @Yimura What is the requirement for removing it?

Based the original post description, it seems like needless noise that can be removed.

**Comment by gir489returns** [comment]
I think it's fine the way it is. If you restore Casino Pachio to its original state and io.open operates the way it should according to the documentation, no WARNING should be filed in the console. This ticket is purely user error. I think sending a WARNING to the console when the user tried to run a script for a file that expected to be there that is not there is perfectly fine as xiao pointed out.

**Comment by Yimura** [comment]
Alrighty, I couldn't quite comprehend the issue at hand really. This way we can close another one.

**Comment by pierrelasse** [comment]
Idk if someone is asking this but the message was made to say to devs "Oh this file doesn't exist, so we can't open it".
Now problem is that it is a warning, and a warning normally indicates that something is going wrong.
My point was that you can't "safely" open the file. E.g. you can't check if the file exits and then create it, or suppress the warning.
A way to fix it, is to implement a way to check if a file exists, remove the warning, add a way to suppress the warning, or say go fk urself. :)
