### ISSUE TITLE
[Bug]: Massive false-positive report on cheating at the end of a heist.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2572]
### Describe the bug

At the end of Series A - Trash Truck, I got 3 notifications that the people in the lobby were detected as modders. I went to check why and it said because of super jump violations.

### Steps To Reproduce

Complete Series A - Trash Truck.

### Expected Behavior

Should not false flag people as modders.

### Logs and/or screenshots

![image](https://github.com/YimMenu/YimMenu/assets/100792176/1bcd035c-5590-4a02-a7e2-5673635ae368)

```
[00:28:34.6071430][WARN/reaction.cpp:60] Received Modder Detection from JoanC2P ()
[00:28:34.6421148][WARN/reaction.cpp:60] Received Modder Detection from MedicRus ()
[00:28:34.7456561][WARN/reaction.cpp:60] Received Modder Detection from breezytyyyyyyyy9 ()
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by D-Borkan** [comment]
In this case, it is preferable to send a notification, for example, “player name” uses super jump

**Comment by lonelybud** [comment]
> In this case, it is preferable to send a notification, for example, “player name” uses super jump

nah he means that those players he played with were not modders

**Comment by navmodder** [comment]
Sorry unrelated question. Is maybegreat you're alt? Just wondering.

**Comment by Yimura** [comment]
> Sorry unrelated question. Is maybegreat you're alt? Just wondering.

No and why would it matter?

**Comment by gir489returns** [comment]
> Sorry unrelated question. Is maybegreat you're alt? Just wondering.

…Are you asking me if @maybegreat48 and I are the same person?

**Comment by navmodder** [comment]
Sorry just a thought. Sorry Sorry Sorry Sorry Sorry

**Comment by D-Borkan** [comment]
> > In this case, it is preferable to send a notification, for example, “player name” uses super jump
> 
> nah he means that those players he played with were not modders

yeah i test it,  they detection as modder while they not use mod
