### ISSUE TITLE
[Bug]: 'Hide God Mode' no longer works

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2640]
### Describe the bug

It does not hide you being in godmode from other players

### Steps To Reproduce

Enable Network->Spoofing->Hide God Mode
Go on other account with ESP
Go to your other account
See that you have godmode in ESP

### Expected Behavior

No godmode

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
damn

**Comment by pierrelasse** [comment]
> damn

???. Update breaking lotta things or what does this mean? xD

Edit: In a diff session, the hide godmode works. Idfk

**Comment by lonelybud** [comment]
> Edit: In a diff session, the hide godmode works. Idfk

so its working and not working

**Comment by pierrelasse** [comment]
Exactly

**Comment by pierrelasse** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/76223390/0c20371b-329e-4bfe-a29f-845a313561b8)
![image](https://github.com/YimMenu/YimMenu/assets/76223390/a8f66caf-07b7-4706-886c-a6a273fa0b29)
????

**Comment by lonelybud** [comment]
> pierrelasse

by bad accept again. dont send picture here. Test this god mod stuff with me thats why i sent

**Comment by pierrelasse** [comment]
Could not repro
