### ISSUE TITLE
[Request]: 'Hide God Mode' also hides vehicle godmode

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2641]
### Problem

Modders can see your vehicle being in godmode

### Solution

Hide the godmode status of your vehicle like that of your character

### Reason

abcdefg

**Comment by D-Borkan** [comment]
hide godmode already in menu
but for vehicle idk if exist or no

**Comment by pierrelasse** [comment]
It doesn't exist. That's why i'm making this issue.

**Comment by TheGreenBandit** [comment]
This could be done by writing to the entity game state data node

**Comment by pierrelasse** [comment]
But this will only change it in the sent data. Not actually right?

**Comment by TheGreenBandit** [comment]
> But this will only change it in the sent data. Not actually right?

Yes, same way the write player game state data node does. Just writing to the getter for it and returning the values u want.
