### ISSUE TITLE
[Request]: There are no functions to get the radio Station of a car

### ISSUE THREAD

**Issue by Vitamin-X** [YimMenu/YimMenu#2761]
### Problem

CFX.GET_VEHICLE_RADIO_STATION_INDEX dont exist

### Solution

Add GET_VEHICLE_RADIO_STATION_INDEX to VEHICLES
or
Add CFX in generell

### Reason

cant sync the radios between cars

### Additional context

or havent i just not found the function?

**Comment by gir489returns** [comment]
CFX is not a valid/real native table, you're probably referencing some bullshit from a paycheat or something.

The AUDIO native table has what you are looking for. The radio station is not specific to a vehicle.

**Comment by Vitamin-X** [comment]
there is already a setter so why no getter?
`AUDIO.SET_VEH_RADIO_STATION(veh, station)`

and im referencing the FiveM Native Database ( https://docs.fivem.net/natives/?_0x57037960 ) cuz its the best to find stuff and i even helped with it

but i also have just notice that its part of OneSync and they got it inside the same decorator where the lightstate and engine state and such is saved, anyway taking later a look into the GTA source code and see how they done it, atleast the Audio Native Table didnt got at all what im looking for, i can just get the radiostation im on and not other players

**Comment by Yimura** [comment]
CFX are FiveM only natives, they don’t exist in vanilla GTA. Use https://natives.gta.menu for all the supported natives in YimMenu.

**Comment by lonelybud** [comment]
try this code https://github.com/lonelybud/lonelyMenu/blob/fb2d4749f8d044a0c034f2bc45e2afc250f5e3f2/src/views/vehicle/view_vehicle.cpp#L309-L342
