### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ellazia** [YimMenu/YimMenu#2777]
### Describe the bug

I'm trying to use my brother's hack, but the mouse cursor keeps getting stuck in the middle, what should I do?

### Steps To Reproduce

When I ran the dll file and checked it after accessing GTA5, the mouse cursor was stuck in the middle

### Expected Behavior

My computer mouse is fixed to the robe stand

### Logs and/or screenshots

```
<paste your logs here>
```
![스크린샷 2024-02-25 150905](https://github.com/YimMenu/YimMenu/assets/160131813/32db0aea-ffd3-4337-a8f2-4ae392005a8a)

### Store

Rockstar

### Language

Korean

### YimMenu Language

Korean (KR)

### Additional context

Please I wish I knew the solution

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
Go to your settings in game and change the mouse input mode to raw
