### ISSUE TITLE
[Bug]: Cursor stay in the middle

### ISSUE THREAD

**Issue by Ellazia** [YimMenu/YimMenu#2779]
### Describe the bug

말그대로 임메뉴의 핵을 사용하려고 마우스를 움직이니 안움직입니다.

### Steps To Reproduce

화면 가운데에 마우스 고정되다

### Expected Behavior

화면 가운데에 마우스 고정버그

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

Korean

### YimMenu Language

Korean (KR)

### Additional context

해결해주세요!!!!!!!!!!!!

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by V1RU513N** [comment]
Go to your settings in game and change the mouse input mode to raw
