### ISSUE TITLE
[Bug]: Crash by angry modder. boost_behavior.cpp mb caused it

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2791]
### Describe the bug

Angry modder crashes game

### Steps To Reproduce

1. Angry the same modder
2. Get him to crash you
3. Get errors in console

### Expected Behavior

Modder is angry because nothing happens

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14448629/cout.log)

This mb interesting (only place where yimmenu path is)
```
Dumping stacktrace:
[0]	X:\YimMenu\src\backend\looped\vehicle\boost_behavior.cpp L: 10 big::looped::vehicle_boost_behavior
[1]	X:\YimMenu\src\backend\backend.cpp L: 108 big::backend::vehicles_loop
[2]	X:\YimMenu\src\script.cpp L: 101 big::script::fiber_func
[3]	X:\YimMenu\src\script.cpp L: 27 `big::script::script'::`2'::<lambda_1>::operator()
[4]	X:\YimMenu\src\script.cpp L: 28 `big::script::script'::`2'::<lambda_1>::<lambda_invoker_cdecl>
[5]	KERNELBASE.dll PackageIdFromFullName
[6]	ntdll.dll RtlUserFiberStart
[7]	GTA5.exe+0x162EEC0 0x7FF60D8AEEC0
[8]	GTA5.exe+0x1494 0x7FF60C281494
[9]	GTA5.exe+0x130538F 0x7FF60D58538F
[10]	GTA5.exe+0x1821344 0x7FF60DAA1344
[11]	KERNEL32.DLL BaseThreadInitThunk
[12]	ntdll.dll RtlUserThreadStart
[13]	KERNEL32.DLL BaseThreadInitThunk
[14]	ntdll.dll RtlUserThreadStart
[15]	KERNEL32.DLL BaseThreadInitThunk
[16]	ntdll.dll RtlUserThreadStart
[17]	ntdll.dll RtlUserThreadStart
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

Stand kid i think. Atleast it was a smooth noclip

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
Hmmm. I don't think correlation is causation here. 

The line in question for the log is:

`auto* const vehicle = g_local_player->m_vehicle;`

That would mean that somehow g_local_player has been nulled or dereferenced somehow. However, your tiny log snippet can't tell me what the exception fault was, so I can only guess it was a null pointer exception.

My guess is he either did something to you that caused the nullification of g_local_player, and since we don't sanity check it here, it caused a fault, or, g_local_player was nulled normally, and this loop failed to exit gracefully.

@maybegreat48 What do you think?

**Comment by Yimura** [comment]
This crash is not relevant to boost_behavior.cpp as before it comes a different crash log. Whenever you crash the first one is the important one, all the ones that come below it are just the consequence of trying to ignore the crash and keeping the game running.

**Comment by xiaoxiao921** [comment]
Commit hash is way too old, invalid issue.

**Comment by pierrelasse** [comment]
Oh now i know why it didnt update bec xenos had the old version selected. Sorry

**Comment by maybegreat48** [comment]
> @maybegreat48 What do you think?

Null checks are always nice to have. But I don't think that's the cause here

**Comment by pierrelasse** [comment]
Offtopic question but what is causing the stacktrace to contain the path to the file? The pbd something file in the folder with all the .obj files? Maybe this could also be provided so when a error occurs, people can reproduce with a more useful stacktrace.

**Comment by Yimura** [comment]
> Offtopic question but what is causing the stacktrace to contain the path to the file? Ghe pbd something file in the folder with all the .obj files? Maybe this could also be provided so when a error occurs, people can reproduce with a more useful stacktrace.

The pdb is exactly why they’re visible, one issue with pdb’s however is that their path is hardcoded to the path of the original build by default. We’ll have to adapt our build pipeline make a bit more dynamic or patch the dll on disk/at runtime with a custom launcher.

**Comment by pierrelasse** [comment]
Do you mean that the paths in the pbd are absolute and are not correct for users? Maybe it could be patched that the path is made relative or with a made up prefix. For example: C:/github/does/workflow/stuff/Yimmenu/src... to X:/src...

**Comment by xiaoxiao921** [comment]
> > Offtopic question but what is causing the stacktrace to contain the path to the file? Ghe pbd something file in the folder with all the .obj files? Maybe this could also be provided so when a error occurs, people can reproduce with a more useful stacktrace.
> 
> The pdb is exactly why they’re visible, one issue with pdb’s however is that their path is hardcoded to the path of the original build by default. We’ll have to adapt our build pipeline make a bit more dynamic or patch the dll on disk/at runtime with a custom launcher.

I'm failing to see how this is required at all, tools ranging from debuggers, decompilers or IDEs don't really care about the path embedded in the .exe, it's just a suggestion

**Comment by pierrelasse** [comment]
Not required, just making it easier to find what caused the problem and where.

**Comment by xiaoxiao921** [comment]
> Not required, just making it easier to find what caused the problem and where.

Learn to read.

**Comment by pierrelasse** [comment]
Already done

**Comment by xiaoxiao921** [comment]
? The pdb path is irrelevant like I said just above, you can't read
