### ISSUE TITLE
[Bug]: Script patches are not undone during module ejection.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2887]
### Describe the bug

[script_patch_service](https://github.com/YimMenu/YimMenu/blob/master/src/services/script_patcher/script_patch.cpp) never undoes its patch when ejecting.

### Steps To Reproduce

Inject YimMenu
Eject YimMenu
Reinject YimMenu
Script VM is patched twice for some reason.

### Expected Behavior

When the module is ejected, all script patches should be undone.

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Rxann** [comment]
Looks like the vectors of script patches just get cleared and don't actually get restored
