### ISSUE TITLE
[Request]: Please add an option for robbery

### ISSUE THREAD

**Issue by 05740682** [YimMenu/YimMenu#2961]
### Problem

After the robbery began
When protection and reaction are all enabled, there will be some problems with robbery

### Solution

When I enable trust this session, everything works fine
But it needs to be re-enabled every time you start a robbery, please add an option to detect if it is a robbery then trust the session directly
Or is there a better solution?

![yimmenu](https://github.com/YimMenu/YimMenu/assets/48167619/cce5835b-592b-4cfd-9398-f2d75dd4e520)

### Reason

After all protection and reaction are enabled
Sometimes the robbery gets stuck.

**Comment by rkwapisz** [comment]
What problems? Is something not spawning?

**Comment by gir489returns** [comment]
Please revisit the protections one-by-one. They have tooltips that tell you things, like they may block this kind of thing. Don't just turn on all protections and then expect things to work properly. While we should revisit them with knowledge we've gained over the years and fix them, we have much more pressing issues at the moment, mostly that a lot of people have stopped working on the project.

**Comment by 05740682** [comment]
Robbery at the casino, entering the main gate, may get stuck on the black screen
and you can't plant bombs in the vault room

**Comment by 05740682** [comment]
I understand that all protection should be turned off to play robbery
But when the robbery is over, will join a public session
Some modder will try to teleport me somewhere and kill me 
It makes me angry.

**Comment by Akshansh16** [comment]
Check your protections again and set the reaction against them.

I have completed robbery ~ Casino Heist 2 times and Cayo Heist one time with all the protections enabled and didn't get any issues!
