### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kolhax** [YimMenu/YimMenu#2974]
### Describe the bug

Seems like every users are ender the ground and visually i cannot net see them
like we dont see in this screenshot but it chased him and never saw him / his car, was just running on radar,
till i realized everyone else is underground!?

### Steps To Reproduce

I just injected it.

### Expected Behavior

Work as a normal cheat?

### Logs and/or screenshots

![image](https://github.com/YimMenu/YimMenu/assets/92904192/c2cb7dcb-a590-4a55-b0ad-5a3a763bbcac)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment]
No log file provided, the mod menu works as intended on my end so we can't really help you further until you provide that.

**Comment by gir489returns** [comment]
> No log file provided, the mod menu works as intended on my end so we can't really help you further until you provide that.

![image](https://github.com/YimMenu/YimMenu/assets/100792176/8797f9d5-3e77-41ee-80bf-e13c3e193d94)

**Comment by Kolhax** [comment]
> No log file provided, the mod menu works as intended on my end so we can't really help you further until you provide that.

Please before closing just ask. Supplementary questions first, let me send the log

**Comment by Yimura** [comment]
You can still provide the menu log and we can reopen it.

**Comment by Kolhax** [comment]
[cout.log](https://github.com/YimMenu/YimMenu/files/15131864/cout.log)

**Comment by gir489returns** [comment]
You were being attacked by someone manipulating the remote data.

**Comment by Kolhax** [comment]
> You were being attacked by someone manipulating the remote data.

Everytimes I inject it to my gta? its not the first time, NOW, if I go and inject it, it will do the same thing

**Comment by Yimura** [comment]
Can you provide your settings.json file? You may need to change the file extension to .txt

**Comment by gir489returns** [comment]
> > You were being attacked by someone manipulating the remote data.
> 
> Everytimes I inject it to my gta? its not the first time, NOW, if I go and inject it, it will do the same thing

You only included one log, and like YIm stated it works fine on our machines. You'll have to give us more to go on here. You just expect us to know everything about your system and how it works and fix this (very non) issue.

**Comment by Kolhax** [comment]
so?

**Comment by Yimura** [comment]
I have to work during the day and have other things to do besides checking bug reports on this project so I haven't checked it yet.

**Comment by Kolhax** [comment]
> I have to work during the day and have other things to do besides checking bug reports on this project so I haven't checked it yet.

Alr take this relax lmk when you are able to check this, incase here is my discord: kepardev.  Thanks again

**Comment by Kolhax** [comment]
hey

**Comment by gir489returns** [comment]
It's the weekend bro, FO.

**Comment by Kolhax** [comment]
mbd sorry, jesus, i was just asking sorry for asking help I guess

**Comment by gir489returns** [comment]
> and?

Nothing I can see from your settings. Try moving the entire YimMenu folder in AppData to the desktop, see if the bug goes away.

**Comment by heni015** [comment]
I had the same that he had only 1 time, 2players in car driving typically on a road at radar, but  ESP showing me them underground. I don't saw them at road. Maybe they got other IPL of map loaded or something underground and driving without anything. Idk
