### ISSUE TITLE
[Request]: Please add an option to turn off advertiser protection

### ISSUE THREAD

**Issue by 05740682** [YimMenu/YimMenu#2982]
### Problem

When I was playing with my friends
Sometimes he is detected as a spammer
I can't see his words anymore

### Solution

Settings-Protection
Add a checkbox that allows the protection of advertisers to be turned off

![yimmenu_2](https://github.com/YimMenu/YimMenu/assets/48167619/f6101194-e373-41ed-ad12-d6d639bc4162)
![yimmenu_3](https://github.com/YimMenu/YimMenu/assets/48167619/a9edfe8e-a2b9-494d-95bb-e52fb6f2055d)

### Reason

I want to turn off advertiser protection so I can see my friend's words

**Comment by gir489returns** [comment]
Can you post the spam.log located in %appdata%\YimMenu\spam.log

**Comment by pierrelasse** [comment]
https://github.com/YimMenu/YimMenu/issues/1976
Should I make a PR that adds a setting to disable this feature?

**Comment by maybegreat48** [comment]
Or we can simply whitelist friends since they're probably not spammers anyway

**Comment by pierrelasse** [comment]
I can't remember that the spammer status is saved in the player db, so this woule be good to add to be able to remove spammer status. And the spam messages could be logged there instead of spam.log.

**Comment by 05740682** [comment]
> Can you post the spam.log located in %appdata%\YimMenu\spam.log

(Static Detection) [04/29/2024 06:39:35:529 AM] dngeqw (250413371) <39.84.13.166> [ALL]: 304 【线上手工】稳定零封【地堡研究】搜索小程序【阿星电玩】 【全套解琐】绝版豪车【金币等级】徽信小程序【阿星电玩】 【线上科伎】终身售后【封号包赔】搜索小程序【阿星电玩】
(Static Detection) [04/29/2024 06:39:42:037 AM] dhf3kgd (250852744) <UNKNOWN> [ALL]: 0【线上刷金】【十元十亿】【不用上号】微信搜索：GTAA55 【线上科技】【无敌传送】【战局皇帝】微信搜索：GTAA55 【跳过前置】【修改分红】【永久售后】微信搜索：GTAA55
(Static Detection) [04/29/2024 06:39:42:214 AM] olIIlILP (234727772) <UNKNOWN> [ALL]: 826【线上模式-几百亿钱-等级提升】【微信小程序：老八线上】  【微信小程序搜：老八线上】 不死-瞬移-踢出-喷水-爆炸-跳前置套笼子【外挂官网 GTAWG.CN】 【辅助官网 GTAWG.CN】
(Static Detection) [04/29/2024 06:58:08:692 AM] ChineseAchin (211508540) <59.37.129.12> [ALL]: 我卡了。  给你弄刷钱
(Static Detection) [04/29/2024 07:01:26:131 AM] llikk0407 (236038500) <122.10.163.121> [ALL]: 要赚钱打多几个句号给我发信息
(Static Detection) [04/29/2024 07:03:42:395 AM] Her-said (108072981) <113.142.72.53> [ALL]: 有挂
(Static Detection) [04/29/2024 07:07:57:289 AM] dg3hhf (250852838) <1.194.56.206> [ALL]: 0【线上刷金】【十元十亿】【不用上号】微信搜索：GTAA55 【线上科技】【无敌传送】【战局皇帝】微信搜索：GTAA55 【跳过前置】【修改分红】【永久售后】微信搜索：GTAA55
(Static Detection) [04/29/2024 07:09:58:566 AM] sdfhf364 (250996533) <223.155.160.40> [ALL]: 521 【进网站送一亿金币一个高端外挂】【24小时领取网址gtacc.cc】 【进网站送一亿金币一个高端外挂】【24小时领取网址gtacc.cc】 【进网站送一亿金币一个高端外挂】【24小时领取网址gtacc.cc】

**Comment by 05740682** [comment]
I didn't save the log before, and after a few days of trying, the problem came again
They were using Chinese, and I noticed that it seemed like there were a few words in their message that would lead to being detected as an advertiser.

**Comment by gir489returns** [comment]
> I didn't save the log before, and after a few days of trying, the problem came again They were using Chinese, and I noticed that it seemed like there were a few words in their message that would lead to being detected as an advertiser.

Who in the log is your friend?

@sch-lda Can you take a look at his log and see if each person was actually spamming/advertising?

**Comment by sch-lda** [comment]
(Static Detection) [04/29/2024 06:58:08:692 AM] ChineseAchin (211508540) <59.37.129.12> [ALL]: 我卡了。 给你弄刷钱
(Static Detection) [04/29/2024 07:01:26:131 AM] llikk0407 (236038500) <122.10.163.121> [ALL]: 要赚钱打多几个句号给我发信息
(Static Detection) [04/29/2024 07:03:42:395 AM] Her-said (108072981) <113.142.72.53> [ALL]: 有挂

The above messages appears to be sent by human, and the first and the last one are clearly not ADs
Currently, yimmenu has blacklisted Chinese individual characters such as "money" "earn" and "hack" This may be the reason for false positive
If someone send "cheater"/"hacker" in Chinese,he will be flaged

**Comment by gir489returns** [comment]
@Yimura The current system seems to be doing more harm than good in the Chinese realm, at least for this individual. @sch-lda Have you personally had issues? We spoke previously about rolling back the system to just use Rockstar's chat filter. I think we should do that and wash our hands of this issue pushing the problem to Rockstar.

**Comment by sch-lda** [comment]
I will provide an optimized keyword blacklist later

**Comment by 05740682** [comment]
They're not my friends, logs are from public sessions

**Comment by sch-lda** [comment]
![Screenshot_20240429-085303](https://github.com/YimMenu/YimMenu/assets/54973190/680a1e01-aa22-44a1-98d5-ed7e4f0eacbb)
I already have an optimized blacklist that removed some single character and add more words instead.
The false positive probability will significantly decrease, but the black list will become longer.

**Comment by gir489returns** [comment]
@sch-lda Can you make a PR?

@05740682 None of the people in your spam.log are your friend? That doesn't make any sense, it shouldn't be marking them as chat spammers and not sending their chat to spam.log.

**Comment by 05740682** [comment]
> @sch-lda Can you make a PR?
> 
> @05740682 None of the people in your spam.log are your friend? That doesn't make any sense, it shouldn't be marking them as chat spammers and not sending their chat to spam.log.

But it will also happen to my friend
If their message contains some words, they are detected as spammers


I think disable spammer protection 
Is a better choice

**Comment by gir489returns** [comment]
> But it will also happen to my friend If their message contains some words, they are detected as spammers

That's not what I asked. They can't be detected and not be in the log, it's not possible.

**Comment by 05740682** [comment]
> > But it will also happen to my friend If their message contains some words, they are detected as spammers
> 
> That's not what I asked. They can't be detected and not be in the log, it's not possible.

Yes they shouldn't be in spam.log

**Comment by lonelybud** [comment]
@gir489returns remember #2488 that was implemented I think it can cause problem too since chinese uses surrogate pairs basically double the length for each word.

**Comment by lonelybud** [comment]
> @gir489returns remember #2488 that was implemented I think it can cause problem too since chinese uses surrogate pairs basically double the length for each character.

but still it should not be an issue here bcz i tested it on chinese spammers before. not to worry about

**Comment by 05740682** [comment]
The same thing happened in a robbery

chat.log

--------------------------
[04/29/2024 07:30:35:611 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: reaaaadddddddddddddddddyyyyyyyyyyyyyyyyyyyyyyyyyy
[04/29/2024 07:30:53:339 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: aaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
[04/29/2024 07:31:06:076 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: SSSSSSSSSSSSSSSSSSSSHHHHHHHHHHHHHHHHHHDDDDDDDDDDDDDDDDDDDDYYYYYYYYY
[04/29/2024 07:31:47:732 PM] SHAD00WS (250161319) <196.64.20.89> [ALL]: its alpha
[04/29/2024 07:32:04:268 PM] alpha123401 (205013086) <UNKNOWN> [ALL]: IM DONE MAN
[04/29/2024 07:32:04:339 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: yes
[04/29/2024 07:32:13:025 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: hi
[04/29/2024 07:32:34:904 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: ready mf
[04/29/2024 07:32:38:987 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: fffffff
--------------------------

spam.log

--------------------------
(Static Detection) [04/29/2024 07:32:49:551 PM] Ibraproo (122187031) <UNKNOWN> [ALL]: ddddqqqqqqqqqqqdwefcwwereverfr
--------------------------

**Comment by gir489returns** [comment]
@05740682 Can I ask if your friend has Autism? 

It's detecting him as a spammer for sending absolute nonsense, but also sending qq which is a chinese chat platform.

**Comment by 05740682** [comment]
> @05740682 Can I ask if your friend has Autism?
> 
> It's detecting him as a spammer for sending absolute nonsense, but also sending qq which is a chinese chat platform.

lol,because someone was AFK before the robbery started.
