### ISSUE TITLE
[Bug]: Vehicle -> Repair does not fix cars that been in water.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#2995]
### Describe the bug

When a vehicle enters water, it dies completely. Pressing the repair button does not bring the vehicle back to working order.

### Steps To Reproduce

1. Spawn a car.
2. Drive it into a body of water so much so that the car is submerged and dies.
3. Using whatever method, get the car out of the water.
4. Navigate to Vehicle -> Repair and click the button.

### Expected Behavior

Vehicle should restart.

### Logs

![image](https://github.com/YimMenu/YimMenu/assets/100792176/184d9fd5-1632-4938-bf61-27516e2d653d)

### Screenshots / Video

https://github.com/YimMenu/YimMenu/assets/100792176/bb7bff6d-106e-41cf-b492-4d586bd124b6

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by rkwapisz** [comment]
I remember this one being a doozy in ENT, never could figure it out.

All I could figure out is that whatever "destroys" the car when it's in water (and water collision isn't disabled) is the same thing that destroys a car when it's hit by grenades/RPGs/etc, which was somewhat obvious.

In the past I tried using IS_PED_IN_ANY_VEHICLE, passing false in arg2 and was able to visually repair even detonated vehicles that the ped was no longer inside of, but I could not re-enter the vehicle, so it was useless. The vehicle handle is still relevant when the car is destroyed, there's just something behind the scenes that isn't being properly reset with natives like SET_VEHICLE_FIXED or SET_VEHICLE_ENGINE_HEALTH.
