### ISSUE TITLE
[Request]: Allow request control

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2999]
### Problem

I need to uninject for other players to be able to tow me with a tow truck.

### Solution

Add a option to protections to disable it. Or whitelist friends etc.

### Reason

To be able to get towed :D

### Additional context

`src/hooks/protections/received_event.cpp` at `case eNetworkEvents::REQUEST_CONTROL_EVENT:`

**Comment by rkwapisz** [comment]
Have you tried the Trust Player or Trust Friends settings?

**Comment by pierrelasse** [comment]
> Have you tried the Trust Player or Trust Friends settings?

This is not checked in the code
