### ISSUE TITLE
[Bug]: More Info's Bank information is wildly inaccurate. 

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#3008]
### Describe the bug

When opening a player's More Info dialog, the bank information is not correct.

### Steps To Reproduce

Open YimMenu's INSERT menu.
Click on a player.
Click More Info.
Bug appears.

### Expected Behavior

Should display the amount of money the player has.

### Logs

![image](https://github.com/YimMenu/YimMenu/assets/100792176/a1c4f7c2-c189-4ca6-964d-a6e744debeb2)

### Screenshots / Video

![image](https://github.com/YimMenu/YimMenu/assets/100792176/e8150a5e-5d63-4f23-9175-8fcda93496a5)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GreySideMM** [comment]
> Seems to have been a one time issue?

It worked for me some time ago without obvious issues. (I haven't used it / played much since 1.5 month or so.)
