### ISSUE TITLE
[Improvement]: Display player godmode above vehicle godmode in esp

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#3117]
### Which feature

Settings -> ESP

### Reason

To know if the player is in godmode to. Vehicle godmode can be set by other modders, but the player driving doesn't have to be modding. This would let you know if the player is also in godmode thus modding.

### Additional context

`GOD`
`Vehicle God Mode` 

is not very similar. idk how to make it better tho

**Comment by lonelybud** [comment]
https://github.com/YimMenu/YimMenu/blob/44269fcf35f71e7e038ab4d70c1b3be841ec1e59/src/views/esp/view_esp.cpp#L85-L102

https://github.com/YimMenu/YimMenu/blob/44269fcf35f71e7e038ab4d70c1b3be841ec1e59/src/views/settings/view_esp_settings.cpp#L38

check is present right

**Comment by pierrelasse** [comment]
Weird. Is godmode spoofed as disabled when your vehicle is in godmode by default in gta?

**Comment by rkwapisz** [comment]
Here's a hint:

https://github.com/YimMenu/YimMenu/blob/44269fcf35f71e7e038ab4d70c1b3be841ec1e59/src/views/esp/view_esp.cpp#L108-L110

**Comment by pierrelasse** [comment]
=+ instead of +=? dis a tresure hunt or what xd

**Comment by rkwapisz** [comment]
There you go! Now submit a PR for that sucker.

**Comment by pierrelasse** [comment]
yay. ill do that later when I'm on pc. Thanks for the help.
