### ISSUE TITLE
[Bug]: I can't sell goods from the bunker

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#3151]
### Describe the bug

After injecting the menu, I can't deliver goods from the bunker to the customer. At first, after picking up the transport, I teleported to the delivery location and thought the problem was that robbers weren't spawning in time or something like that, but no. When I drove from point A to point B, I also couldn't deliver. I just stand at the point, press the button, and the goods don't drop off.

### Steps To Reproduce

1. Load into the session with an injected menu
2. Launch the sale of weapons from the bunker
3. Get into one of the cars with goods
4. Reach the yellow point on your own
5. When trying to discard the item, nothing happens.

### Expected Behavior

The goods must be delivered.
P.S. The same situation is happening with some of the motorcycle club businesses, the business battle, and possibly something else. Could something be interfering during delivery? Has no one encountered this issue before?

### Logs

None

### Store

Steam

### Language

Russian

### YimMenu Language

Русский (RU)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ghost** [comment]
I'm so sorry, this is a duplicate of #1808

**Comment by gir489returns** [comment]
@CringeArab Was the solution posted with #1808 work for you?

**Comment by ghost** [comment]
> @CringeArab Was the solution posted with #1808 work for you?

That’s why I created this issue, because after calmly driving from the bunker to the yellow dot, I still couldn’t deliver the weapon.  Perhaps the reason for this was that I was the host and used fast join, which probably broke the mission.  I'll try to do this tomorrow without a session host and a quick connection, if anything happens I'll write back
P.S. Disabling "fast join" and "force script host" solved my problem
