### ISSUE TITLE
Yimmenu is dead?

### ISSUE THREAD

**Issue by Is-YimMenu-dead** [YimMenu/YimMenu#3178]
### Describe the bug

The menu was last updated in 2023, can it be used?

### Steps To Reproduce

What

### Expected Behavior

I just wanted to ask, have you abandoned the project or not? I’ve seen reviews of your menu from different bloggers, but they always have links to .exe files that download something unclear.  and the last update date on your website is 2023.  Is the menu still up to date?

### Logs

No log sry

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment]
![image](https://github.com/YimMenu/YimMenu/assets/837334/f29fa85a-2d0f-4f28-ae72-b9822e0b20f9)


![image](https://github.com/YimMenu/YimMenu/assets/837334/df0ffd7d-089b-4d54-9b16-5a5a75aab263)
