### ISSUE TITLE
[Improvement]: Please improve chat spam protection

### ISSUE THREAD

**Issue by gfhghfghfhgfyututyuykyghgn** [YimMenu/YimMenu#3202]
### Which feature

Is it possible to block links to discord?

### Reason

Many people simply advertise discord with mods/cheats
![screen](https://github.com/YimMenu/YimMenu/assets/171228691/52aaca00-4949-441e-9adc-9945eb2c0b7f)

**Comment by Rxann** [comment]
I will add some things to the blacklist that are in your image.

**Comment by eggrolls-repu** [comment]
i just manually add all bots to my blocklist with block join on
