### ISSUE TITLE
[Bug]: game crashed

### ISSUE THREAD

**Issue by 05740682** [YimMenu/YimMenu#3339]
### Describe the bug

I joined the public session as usual, and 20 minutes later, a modder started attacking me and my game crashed.
I'm not sure if the crash was caused by a modder or some other reason.

### Steps To Reproduce

1. "Joined a public session."
2. "Got attacked by a modder."
3. "Game crashed."

### Expected Behavior

game won't crash

### Logs

[cout.log](https://github.com/user-attachments/files/16194145/cout.log)

### Store

Steam

### Language

Simplified Chinese

### YimMenu Language

Chinese (CN)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment]
This is related to #3340.

**Comment by maybegreat48** [comment]
> This is related to https://github.com/YimMenu/YimMenu/issues/3340.

It looks like a different crash to me. The other one crashes in the packet sender and this one crashes in the renderer

**Comment by 05740682** [comment]
Confirmed, this issue is the same as #3340 and is not caused by MODDER
