### ISSUE TITLE
[Bug]: Spawning a clone of a personal vehicle ejects you from it, saying this isn't your personal vehicle.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#3448]
### Describe the bug

When spawning a clone of a personal vehicle, you get immediately ejected off the vehicle, and it says you can't use this vehicle because it's a personal vehicle.

### Steps To Reproduce

Spawn a personal vehicle.
Get ejected.

### Expected Behavior

Should be able to drive it.

### Logs

```
[01:23:10.1520166][WARN/prepare_metric_for_sending.cpp:103] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":2,"c":4039289119,"d":0,"e":1,"f":62,"g":100,"h":0,"i":0,"j":false,"k":0,"l":0
[01:23:10.1520474][WARN/prepare_metric_for_sending.cpp:103] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":2,"c":2038480341,"d":0,"e":1,"f":62,"g":100,"h":0,"i":0,"j":false,"k":0,"l":0

```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

https://github.com/user-attachments/assets/5f68125d-0729-4907-8d8c-79dde3cadbdc

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment]
the metric is sent bcz this is called `ENTITY::SET_ENTITY_AS_NO_LONGER_NEEDED(&veh)` but nevertheless if we are able to fix it is nice

**Comment by lonelybud** [comment]
dupe detect metric must be called bcz we call `ENTITY::SET_ENTITY_AS_NO_LONGER_NEEDED` native? https://github.com/YimMenu/YimMenu/discussions/2465#discussioncomment-8269680

**Comment by CypherMorgan** [comment]
Happens with some of the vehicles while spawning from the New Vehicle tab, different for each player... Like for me it would be Cypher and another Yim user, it would be Cyclone (Just for an example).
