### ISSUE TITLE
[Bug]: ERR_MEM_EMBEDDEDALLOC_GUARD_4 Crash

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#3562]
### Describe the bug

Sometimes when joining a session, when detecting a host modder, when the reaction is triggered, I get a crash ERR_MEM_EMBEDDEDALLOC_GUARD_4 and cout is generated infinitely

### Steps To Reproduce

1. Enter the session to the modder host
2. Triggering a reaction to modder detection
3. Be crashed

This doesn't happen all the time but it's the most common crash for me. I also noticed that I saw the modder's nickname in the players' table and it was painted red, but the nickname was not saved in the logs. At the same time, it was saved in the players database. His RID: 164340175

### Expected Behavior

Don't be crashed

### Logs

[cout.log](https://github.com/user-attachments/files/16579908/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

If you need my settings, here they are 
[settings.json](https://github.com/user-attachments/files/16579911/settings.json)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Ahmad23145** [comment]
Out of Memory Crash

**Comment by ghost** [comment]
Is it possible to fix? or my laptop is poor

**Comment by Ahmad23145** [comment]
It's a game memory error, verify game files

**Comment by maybegreat48** [comment]
> I also noticed that I saw the modder's nickname in the players' table and it was painted red

Are you sure?

**Comment by ghost** [comment]
> Are you sure?

I'm sure of it, I remembered his nickname, the player managed to turn red and a notification about cheater detection appeared. and at that moment a crash occurred, but in the players.json file I found his nickname, although not in cout. one could assume that he was already in my player base, but then I would not be able to connect to him because I blocked modders in the session browser.

**Comment by ghost** [comment]
This happened again with a different player but this time the player's name was output to cout and to player.json
![image](https://github.com/user-attachments/assets/2d256a2d-1379-43c6-815b-6b2e6b82c1c7)


Maybe it's a Lua script issue? Here are the logs:
[cout.log](https://github.com/user-attachments/files/16597501/cout.log)

**Comment by Ahmad23145** [comment]
> This happened again with a different player but this time the player's name was output to cout and to player.json ![image](https://private-user-images.githubusercontent.com/177620802/357362915-2d256a2d-1379-43c6-815b-6b2e6b82c1c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzIxMjksIm5iZiI6MTcyMzU3MTgyOSwicGF0aCI6Ii8xNzc2MjA4MDIvMzU3MzYyOTE1LTJkMjU2YTJkLTEzNzktNDNjNi04MTViLTZiMmU2YjgyYzFjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNzU3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODU4NGU0YzU1NjZjMDgzMWZjNDFmN2Y2OTA0NzcxZTA1MzE1ZTM4ODE3NTUxNjg3OTI1MWFmNWQwMDM0YWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rYldqhjIDpdD7B-SHyFU7LIdaI1HT4wk1ry9xk7LCN4)
> 
> Maybe it's a Lua script issue? Here are the logs: [cout.log](https://github.com/user-attachments/files/16597501/cout.log)

Its probably your potatoe pc lol

**Comment by Ahmad23145** [comment]
> > This happened again with a different player but this time the player's name was output to cout and to player.json ![image](https://private-user-images.githubusercontent.com/177620802/357362915-2d256a2d-1379-43c6-815b-6b2e6b82c1c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzIxMjksIm5iZiI6MTcyMzU3MTgyOSwicGF0aCI6Ii8xNzc2MjA4MDIvMzU3MzYyOTE1LTJkMjU2YTJkLTEzNzktNDNjNi04MTViLTZiMmU2YjgyYzFjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNzU3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODU4NGU0YzU1NjZjMDgzMWZjNDFmN2Y2OTA0NzcxZTA1MzE1ZTM4ODE3NTUxNjg3OTI1MWFmNWQwMDM0YWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rYldqhjIDpdD7B-SHyFU7LIdaI1HT4wk1ry9xk7LCN4)
> > Maybe it's a Lua script issue? Here are the logs: [cout.log](https://github.com/user-attachments/files/16597501/cout.log)
> 
> Its probably your potatoe pc lol

 @boogabooga841 Try deleting AppData\Roaming\YimMenu, AppData\Local\Rockstar Games and verify game files
