### ISSUE TITLE
[Request]: I would like to make a proposal for the repair of the vehicle

### ISSUE THREAD

**Issue by Jo3y4r3aL** [YimMenu/YimMenu#440]
### Problem

Can u turn the Repair Vehicle button into an automatic repair?

### Solution

Just add this feature to the vehicle list

### Reason

This can give people like me who have an obsessive-compulsive disorder a good experience
It can also help players better appreciate their cars

**Comment by TheGreenBandit** [comment]
sechsmenu includes this feature in their fork
