### ISSUE TITLE
Error    MSB8013    This project doesn't contain the Configuration and Platform combination of Debug|Win32

### ISSUE THREAD

**Issue by MrChillDev** [YimMenu/YimMenu#454]
How to i fix Error    MSB8013    This project doesn't contain the Configuration and Platform combination of Debug|Win32

**Comment by SkiddyToast** [comment]
Switch the build mode to x64 and Release.

**Comment by Yimura** [comment]
I don't know how you got this error, it shouldn't be possible with the premake5.lua file.

Try setting it to x64 release as SkiddyToast said.

**Comment by MrChillDev** [comment]
i fix it thank you tho
