### ISSUE TITLE
[Request] Esp and aimbot or add recovery like rp or level

### ISSUE THREAD

**Issue by MrChillDev** [YimMenu/YimMenu#455]
Hey do you know some code or could you add Esp and aimbot or add recovery like rp or level

**Comment by SkiddyToast** [comment]
ESP is already in the menu and no recovery options will be added, as to not get Rockstar’s attention.

**Comment by MrChillDev** [comment]
oh wheres esp

**Comment by MrChillDev** [comment]
at in the menu

**Comment by MrChillDev** [comment]
nvm i found it also would you guys ever add aimbot

**Comment by SkiddyToast** [comment]
Someone can make a PR to add it if they want.

**Comment by MrChillDev** [comment]
what does pr stand for

**Comment by SkiddyToast** [comment]
Pull Request

**Comment by Yimura** [comment]
Please refer to https://github.com/YimMenu/YimMenu/discussions/237 on why we don't add recovery or toxic features.
