### ISSUE TITLE
[Request]: YTD loader

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#505]
### Problem

Right now the only type of modded vehicles wr can have are vehicles with objects attached. With a ytd loader we could have a wider range of customizability. 

### Solution

A ytd loader that can work alongside the json loader

### Reason

This would allow for greater customization of vehicles, examples including change the picture on a blimp, changing the logo on the taxi, changing the textures on cars etc.

**Comment by tupoy-ya** [comment]
I think you can try using [ClosedIV](https://github.com/martonp96/ClosedIV) for this, but i think it was broken in #457 and now crashes. Also it doesn't let you go in to public sessions with some mods.

**Comment by TheGreenBandit** [comment]
Yeah, i should also specify for people that dont know what a ytd is, it allows u to replace textures on cars really, like minecraft textures can be changed ytds can be changed, this doesn't change the model however but only the models cover wrap aka texture

**Comment by TheGreenBandit** [comment]
> Yeah, i should also specify for people that dont know what a ytd is, it allows u to replace textures on cars really, like minecraft textures can be changed ytds can be changed, this doesn't change the model however but only the models cover wrap aka texture

I saw something about this in simple menu on unknown cheats too, so if need be take inspiration from that

**Comment by TheGreenBandit** [comment]
closing as not needed, could be accomplished with imgui drawlist
