### ISSUE TITLE
[Request]: gravity gun entity selection

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#507]
### Problem

Currently you can on select one thing with the gravity gun, not being able to pick up multiple entities make it kinda  a bore

### Solution

Be able to select entities to use with the gravity gun

### Reason

General improvement

**Comment by TheGreenBandit** [comment]
Completed in #650

**Comment by Yimura** [comment]
Not yet merged, keeping open till it's merged.
