### ISSUE TITLE
Request: Silent Godmode

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#526]
### Problem

Other modders can detect godmode, kicking you out of the session once they see it

### Solution

Add a option to godmode to have a stealth version

### Reason

Would help prevent other modders detecting you

### Additional context

This can be done by triggering the regen rapidly, however this wouldn't make you invincible to explosions, it would make you invincible silently

**Comment by SkiddyToast** [comment]
This can be easily implemented through the `CPlayerGameStateDataNode` by setting the proofs to false before returning in the writer.

**Comment by FireFox101889** [comment]
> This can be easily implemented through the `CPlayerGameStateDataNode` by setting the proofs to false before returning in the writer.

Do you care to share the sig and hook function?

**Comment by Dan199624** [comment]
> > This can be easily implemented through the `CPlayerGameStateDataNode` by setting the proofs to false before returning in the writer.
> 
> Do you care to share the sig and hook function?

its in the CPlayerSyncTree iirc

**Comment by SkiddyToast** [comment]
> > > This can be easily implemented through the `CPlayerGameStateDataNode` by setting the proofs to false before returning in the writer.
> > 
> > 
> > Do you care to share the sig and hook function?
> 
> its in the CPlayerSyncTree iirc

It’s in the `IPlayerDataNodeAccessor` vtable.

**Comment by FireFox101889** [comment]
> ```c++
> main_batch.add("WPGSDN", "48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 41 54 41 55 41 56 41 57 48 83 EC 30 0F B7 81 ? ? ? ?", [this](memory::handle ptr)
> {
> 	m_write_player_game_state_data_node = ptr.as<functions::write_player_game_state_data_node>();
> });
> bool hooks::write_player_game_state_data_node(rage::netObject* plr, CPlayerGameStateDataNode* node) 
> 	{
> 		auto ret = g_hooking->m_write_player_game_state_data_node_hook.get_original<decltype(&write_player_game_state_data_node)>()(plr, node);
> 		node->m_bullet_proof = false;
> 		node->m_collision_proof = false;
> 		node->m_drown_proof = false;
> 		node->m_explosion_proof = false;
> 		node->m_fire_proof = false;
> 		node->m_steam_proof = false;
> 		node->m_melee_proof = false;
> 		node->m_is_invincible = false;
> 		node->m_is_spectating = false;
> 		node->m_super_jump_enabled = false;
> 		node->m_modified_health = false;
> 		node->m_never_target = false;
> 		node->m_friendly_fire_allowed = true;
> 
> 		return ret;
> 	}
> ```

Yoooo tysm, btw do you have a different class? drown_proof and super_jump_enabled doesn't exist
+rep

**Comment by Aure7138** [comment]
> > ```c++
> > main_batch.add("WPGSDN", "48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 41 54 41 55 41 56 41 57 48 83 EC 30 0F B7 81 ? ? ? ?", [this](memory::handle ptr)
> > {
> > 	m_write_player_game_state_data_node = ptr.as<functions::write_player_game_state_data_node>();
> > });
> > bool hooks::write_player_game_state_data_node(rage::netObject* plr, CPlayerGameStateDataNode* node) 
> > 	{
> > 		auto ret = g_hooking->m_write_player_game_state_data_node_hook.get_original<decltype(&write_player_game_state_data_node)>()(plr, node);
> > 		node->m_bullet_proof = false;
> > 		node->m_collision_proof = false;
> > 		node->m_drown_proof = false;
> > 		node->m_explosion_proof = false;
> > 		node->m_fire_proof = false;
> > 		node->m_steam_proof = false;
> > 		node->m_melee_proof = false;
> > 		node->m_is_invincible = false;
> > 		node->m_is_spectating = false;
> > 		node->m_super_jump_enabled = false;
> > 		node->m_modified_health = false;
> > 		node->m_never_target = false;
> > 		node->m_friendly_fire_allowed = true;
> > 
> > 		return ret;
> > 	}
> > ```
> 
> Yoooo tysm, btw do you have a different class? drown_proof and super_jump_enabled doesn't exist +rep
super_jump_enabled is at 0x1B7
