### ISSUE TITLE
Request: better godmode detection 

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#549]
### Problem

Some menus use a form of godmode where they regen the player every tick

### Solution

Detect for is regenerating along with the original godmode to detect other modders easier, if someone is normally regenning then it will only reggening under them until they're done but if they are using the godmode the regenning will stay there

### Reason

It will provide better godmode detection and detection of other modders

**Comment by Yimura** [comment]
This seems like a useless task to invest time into because godmode and health can be spoofed by the player.

You could even fake your HP going down when taking damage, definitely very low priority if this gets worked on ever.

**Comment by Faint0002** [comment]
That gives me a great idea to spoof those things, thanks! Lmao

**Comment by SkiddyToast** [comment]
> The game's network architecture has no protection against cheaters and therefore everything is managed locally and can be spoofed (even things like name, position and model)

I am actually working on accurately detecting if a player's name is spoofed/changed(without any form of SCAPI) at the moment.

**Comment by TheGreenBandit** [comment]
> The game's network architecture has no protection against cheaters and therefore everything is managed locally and can be spoofed (even things like name, position and model)

maybe some extra spoofing options can be added based off what u said?

**Comment by SkiddyToast** [comment]
> > The game's network architecture has no protection against cheaters and therefore everything is managed locally and can be spoofed (even things like name, position and model)
> 
> maybe some extra spoofing options can be added based off what u said?

It's as easy as finding the writers, hooking them, and changing the contents of the struct they're writing into.

**Comment by TheGreenBandit** [comment]
by the way for the projects thing on github is that even used by yimmenu anymore? because it hasnt been updated in awhile

**Comment by Yimura** [comment]
Added in #641
