### ISSUE TITLE
Bug: Visual Studo

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#561]
### Describe the bug

After generating project files and opening the solution in visual studio, all the files are not in their respective folders

### Steps To Reproduce

Clone menu, generate project files, open solution 

### Expected Behavior

All files should be normal

### Screenshots and/or Logs

![FF1C40EB-A049-4DED-9AC3-1ACEBE3103F8](https://user-images.githubusercontent.com/106003542/200710620-a799fe6c-3d93-46ea-925f-b8aeb87d342c.png)

### Store

Epic Games

### Additional context

Its forcing me to say i used it unmodified but i used tupoya's fork and just updated it to latest version of yimmenu

### Build

- [X] I used YimMenu unmodified

**Comment by tupoy-ya** [comment]
I haven't updated my fork yet

> Its forcing me to say i used it unmodified but i used tupoya's fork and just updated it to latest version of yimmenu

You should open this on tupoy-ya's fork then.

**Comment by Yimura** [comment]
I don't get it if you're not using YimMenu stock then don't come make an issue here, that's what the checkbox is for...

**Comment by TheGreenBandit** [comment]
Yeah but it also happens on my own lmao

**Comment by SpaghettDev** [comment]
I made a fresh copy of YimMenu and also had this problem.

**Comment by Yimura** [comment]
I'm gonna be honest I don't use Visual Studio on CMake projects.
My personal suggestion is to use Visual Studio Code instead.

**Comment by SpaghettDev** [comment]
> I'm gonna be honest I don't use Visual Studio on CMake projects.
> My personal suggestion is to use Visual Studio Code instead.

back when this project used to rely on MSVC, all the files were organized in separate sub-folders (or filters), now every file is in the YimMenu solution, even though in reality each one is in its separate sub-folder.
Nonetheless, I will switch to Visual Studio Code.

**Comment by Yimura** [comment]
The subprojects aren't supposed to be modified directly but instead you're supposed to modify the actual repo and then update it.
I understand that it might be difficult to be aware of which files exists, if you're actively developing on YimMenu then I suggest using a fork and switching back to the old system, shouldn't be too hard to switch back.

**Comment by SpaghettDev** [comment]
Yeah I understand that. For now I'll be using VSCode.
I will make a PR that adds a YimMenu.vcxproj.filters file when I have time, but I'll need to learn how CMake works...
