### ISSUE TITLE
[Bug]:error C2712: Cannot use __try in functions that require object unwinding

### ISSUE THREAD

**Issue by woejefe** [YimMenu/YimMenu#599]
### Describe the bug

when trying to build in VS i am getting this error

YimMenu\src\invoker.cpp(37,23): error C2712: Cannot use __try in functions that require object unwinding

`1>Generating Code...
1>C:\Users\me\YimMenu\src\services\gui\gui_service.cpp(19): error C2220: the following warning is treated as an error
1>C:\Users\me\YimMenu\src\services\gui\gui_service.cpp(19): warning C4172: returning address of local variable or temporary: tab_none
1>Done building project "YimMenu.vcxproj" -- FAILED.`

### Steps To Reproduce

installed visual studio, cmake, and git

cmake compiled correctly and i was able to load solution. When i go to build it the errors pop up and fails to build

### Expected Behavior

to build

### Screenshots and/or Logs

```
Build started...
1>------ Build started: Project: YimMenu, Configuration: Debug x64 ------
1>backend.cpp
1>invoker.cpp
1>C:\Users\me\YimMenu\src\invoker.cpp(37,23): error C2712: Cannot use __try in functions that require object unwinding
1>main.cpp
1>gui_service.cpp
1>view_player.cpp
1>vmt_hook.cpp
1>Generating Code...
1>C:\Users\me\YimMenu\src\services\gui\gui_service.cpp(19): error C2220: the following warning is treated as an error
1>C:\Users\me\YimMenu\src\services\gui\gui_service.cpp(19): warning C4172: returning address of local variable or temporary: tab_none
1>Done building project "YimMenu.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 8 up-to-date, 0 skipped ==========
========== Elapsed 00:06.160 ==========

```

### Store

Steam

### Build

- [X] I used YimMenu unmodified

**Comment by SpaghettDev** [comment]
In Visual Studio, change the "Solution Configurations" to Release. By default it's Debug which can't be built.
Here's what I'm referring to:
![image](https://user-images.githubusercontent.com/37266659/202135643-09d50911-9cd0-4147-b595-0b5774dbae0f.png)

**Comment by woejefe** [comment]
Ah thank you

**Comment by SpaghettDev** [comment]
No problem :) Can you close this issue now?
