### ISSUE TITLE
Unrelated or sorta related to yim

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#647]
I think i missed an update becuase im trying to add a feature but the native i eant to use doesn't seem to be calling, WEAPON::GET_PED_LAST_WEAPON_IMPACT_COORD, i have tested the feature i wanted to add on yim and it worked but when i tested it on my version of yim it did not call the coord resulting in it not working. Anyone know what i might have missed to cause this breakage?

**Comment by TheGreenBandit** [comment]
So im thinking the things i might have missed could he in the invoker, the memory folder or the gta folder

**Comment by Aure7138** [comment]
I can't even inject your fork version, how did you test it
version hash 84d44064243f7b2aebc6707b238022a168d0f168

**Comment by TheGreenBandit** [comment]
> I can't even inject your fork version, how did you test it
> 
> version hash 84d44064243f7b2aebc6707b238022a168d0f168

Oh no its not in my fork, idk wtf changed tho that would cause this error

**Comment by TheGreenBandit** [comment]
> Oh no its not in my fork, idk wtf changed tho that would cause this error

I updated the memory, gta files, and invoker, but the last update i really did from yim was the cmake update

**Comment by Yimura** [comment]
You said it works on a clean YimMenu clone, right?
> i have tested the feature i wanted to add on yim and it worked

**Comment by TheGreenBandit** [comment]
> You said it works on a clean YimMenu clone, right?
> 
> > i have tested the feature i wanted to add on yim and it worked

Yes

**Comment by TheGreenBandit** [comment]
Im just trying to figure out what i missed that's making the native not call the position lmao

**Comment by Aure7138** [comment]
Doesn't it work even if you put it in a button

**Comment by TheGreenBandit** [comment]
> Doesn't it work even if you put it in a button

Nope, the gui doesn't affect it, how i have it its looped to call the last position

**Comment by Yimura** [comment]
Closing this issue as it isn't an issue with the current version of YimMenu.
