### ISSUE TITLE
[Bug]: After you force it to become a session host, everyone leaves the session

### ISSUE THREAD

**Issue by iwanttodo1t** [YimMenu/YimMenu#661]
### Describe the bug

When I turn on Force Session Host, when I become a Session Host, everyone leaves the session

### Steps To Reproduce

.

### Expected Behavior

Is it a problem with my network

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by SkiddyToast** [comment]
You are being kicked because you are attempting to force host. Mod menus can detect this.

**Comment by iwanttodo1t** [comment]
> You are being kicked because you are attempting to force host. Mod menus can detect this.

To avoid being detected by others, I also tested it in sessions with very few people

**Comment by SkiddyToast** [comment]
Are you 100% sure there wasn't a modder in that session?

**Comment by iwanttodo1t** [comment]
> Are you 100% sure there wasn't a modder in that session?

Not sure, I was only able to test multiple times in sessions with only 3 people

**Comment by SkiddyToast** [comment]
Try to get a friend make a invite-only session, have a couple of your friends join without menus, and test it there.

**Comment by iwanttodo1t** [comment]
> Are you 100% sure there wasn't a modder in that session?

Can you succeed in becoming a session host

**Comment by SkiddyToast** [comment]
I haven't tried myself, but I also haven't heard of anyone else having this problem without modders in the session.

**Comment by SkiddyToast** [comment]
The only other way I can think of is that you're the last in the queue, so you're kicking everyone else.

**Comment by unnamed204** [comment]
It happens when Rockstar ID spoofing is enabled

**Comment by Yimura** [comment]
> It happens when Rockstar ID spoofing is enabled

That's one option but not always the cause.

In general there are 2 ways you may end up with an empty session.
1. Spoofing (Name, RID, IP)
2. Forcing Session Host and a modder kicks you

Breakup kick protections works only on people that join after you and requires you to be host.

**Comment by iwanttodo1t** [comment]
After disabling RID spoofing, it successfully becomes a session host
