### ISSUE TITLE
[Bug]: Alt Tab Freezes Game

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#772]
### Describe the bug

Game is frozen when you clikc into game after being tabbed out

### Steps To Reproduce

alt tab out of game with menu open
click on something in another window
go back into gta and its frozen

### Expected Behavior

alt tab cleanly back into game

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Additional context

it unfreezes whenever you doubleclick the map button (esc/p), possible the menu would need to force the map and then close out map when it detects click in game after alt tab to fix crash

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Hydra-Source** [comment]
What's your system? I think that happens on lower end builds/low settings. Can't be sure though i don't have it.

**Comment by TheGreenBandit** [comment]
also there seems to be another bug where auto tp to waypoint will tp you to a different spot than selected, seems to be tping to the spot the map is hovered over instead of the actual waypoint, might be fixed by waiting a second and letting it zoom to the waypoint then tping

**Comment by TheGreenBandit** [comment]
> What's your system? I think that happens on lower end builds/low settings. Can't be sure though i don't have it.

its very inconsistent, for example clinking out of the game to here will not cause me to freeze, but clicking into a youtube video will, but i have GRAPHICS: gtx 1650,  CPU: cORE I3-10100, 16GB of ram, and i am running the game and my os on a ssd with over 500gb availible of space

**Comment by Hydra-Source** [comment]
> > What's your system? I think that happens on lower end builds/low settings. Can't be sure though i don't have it.
> 
> its very inconsistent, for example clicking out of the game to here will not cause me to freeze, but clicking into a youtube video will, but i have GRAPHICS: gtx 1650, CPU: cORE I3-10100, 16GB of ram, and i am running the game and my os on a ssd with over 500gb available of space

![GTA5_MZxpi3iu85](https://user-images.githubusercontent.com/85032105/210009129-68e8960a-e572-4097-9ff3-8ee73136c24f.png)

Have this off.

**Comment by TheGreenBandit** [comment]
> Have this off.

oh thanks lmao

**Comment by TheGreenBandit** [comment]
however the auto waypoint still seems to be broken, so thats another issue entirely

**Comment by Yimura** [comment]
This issue occurs when you have pause on focus loss enabled, just press ESC a few times and the game should become responsive again. This is not an issue with YimMenu but the game incorrectly resuming when tabbing in.
