### ISSUE TITLE
Interior and cutscene check for spoof godmode

### ISSUE THREAD

**Issue by TheGreenBandit** [YimMenu/YimMenu#801]
### Problem

Right now if our player is in interior or a cutscene we wont appear as godmode

### Solution

Add detection for if in cutscene or in interior
if(g.spoofing.spoof_god_mode && !in_interior && !in_cutscene) replace the original part in hooks with this
Will post a interior check and cutscene check in a bit

### Reason

It would help us stay undetected around other modders

**Comment by TheGreenBandit** [comment]
const char* InCutscene(int player)
	{
		if (NETWORK::NETWORK_IS_PLAYER_IN_MP_CUTSCENE(player))
		{
			return true;
		}
		else
		{
			return false;
		}
	}

**Comment by TheGreenBandit** [comment]
bool is_player_in_interior(Player player)
	{
		int interior = INTERIOR::GET_INTERIOR_FROM_ENTITY(self::ped);
		if (!interior) {
			interior = *script_global(2689235).at(player, 453).at(248).as<int*>();
		}
		return interior;
	}

**Comment by Hydra-Source** [comment]
> 	const char* InCutscene(int player)
> 
> 	{
> 
> 		if (NETWORK::NETWORK_IS_PLAYER_IN_MP_CUTSCENE(player))
> 
> 		{
> 
> 			return true;
> 
> 		}
> 
> 		else
> 
> 		{
> 
> 			return false;
> 
> 		}
> 
> 	}

Why const char as a function? Lol.
Also you can just do:

return NETWORK::.......;

No need for if statements.

**Comment by TheGreenBandit** [comment]
yeah, kinda shit code cause i dont knowmuch

**Comment by Hydra-Source** [comment]
> 	bool is_player_in_interior(Player player)
> 
> 	{
> 
> 		int interior = INTERIOR::GET_INTERIOR_FROM_ENTITY(self::ped);
> 
> 		if (!interior) {
> 
> 			interior = *script_global(2689235).at(player, 453).at(248).as<int*>();
> 
> 		}
> 
> 		return interior;
> 
> 	}
> 
> 
> 
> these may have to be modified to fit yimmenu

I don't think you need that script global.

**Comment by TheGreenBandit** [comment]
like this? 

	const char* InCutscene()
	{
		char cutscene = if(NETWORK::NETWORK_IS_PLAYER_IN_MP_CUTSCENE(self::ped))
                return cutscene;
		}
	}
bool is_player_in_interior()
{
	int interior = INTERIOR::GET_INTERIOR_FROM_ENTITY(self::ped);
	}
	return interior;
}

**Comment by FIying-Scotsman** [comment]
> ```
> bool is_player_in_interior()
> {
> 	int interior = INTERIOR::GET_INTERIOR_FROM_ENTITY(self::ped);
> 	}
> 	return interior;
> }
> ```
> 
> these may have to be modified to fit yimmenu

You're likely to cause compile issues as you're returning a non-bool value (an int) in a bool method.

An alternative method could be:

`bool is_player_in_interior()
{
 	return _IS_MINIMAP_IN_INTERIOR();
}`

**Comment by TheGreenBandit** [comment]
> 

ah so like in the info tab you could also use this code and get extra info about the player, ngl thats a good idea

**Comment by TheGreenBandit** [comment]
so would this work as a interior check bool is_player_in_interior(Ped player) { return static_cast<bool>(IS_INTERIOR_SCENE()); }

**Comment by FIying-Scotsman** [comment]
> so would this work as a interior check bool is_player_in_interior(Ped player) { return static_cast(IS_INTERIOR_SCENE()); }

No and why are you casting the type? The native doesn't take any args so you don't need player and IS_INTERIOR_SCENE returns a bool anyway.

In this case it would be identical to what I posted above:

`bool is_player_in_interior() { return IS_INTERIOR_SCENE(); }`

**Comment by TheGreenBandit** [comment]
alright, sounds good

**Comment by FIying-Scotsman** [comment]
> alright, sounds good, holdon found a better native to use GET_INTERIOR_FROM_ENTITY, if we use this instead we can get if others are in interior too, making it not needed to recode another function for the info tab, maybe something like this? inline bool is_player_in_interior(Ped player) { return INTERIOR::GET_INTERIOR_FROM_ENTITY(player); } we would have to implement a check for if i > 0 return true or something
> 
> ```
> inline bool is_player_in_interior(Ped player) { if (INTERIOR::GET_INTERIOR_FROM_ENTITY(player) > 0) return true; }
> ```

You can make that even more streamline by just removing the "return true" bit and getting the method to return the result of the if statement instead. Something like:

`inline bool is_player_in_interior(Ped player) { return if (INTERIOR::GET_INTERIOR_FROM_ENTITY(player) > 0) }`

This way it'll automatically return true/false for us (why work harder when you can work smarter etc etc).

**Comment by TheGreenBandit** [comment]
that wouldn't work though as it's an if statement and expects a expression, thats why i had the return true in, good idea though

**Comment by FIying-Scotsman** [comment]
> that wouldn't work though as it's an if statement and expects a expression, thats why i had the return true in, good idea though

But it does though? The compiler is smart enough to know what to do with it. Similarly you can have a single line if statement without the braces. Again, the compiler is smart enough to know it belongs to the statement and works with it.

**Comment by TheGreenBandit** [comment]
inline bool is_player_in_interior(Ped player) { return (INTERIOR::GET_INTERIOR_FROM_ENTITY(player) > 0); }

**Comment by TheGreenBandit** [comment]
this will work with your idea

**Comment by FIying-Scotsman** [comment]
> ```
> inline bool is_player_in_interior(Ped player) { return (INTERIOR::GET_INTERIOR_FROM_ENTITY(player) > 0); }
> ```
> 
> this will work with your idea also

Definitely. You've got a couple of options to play about with at least. At that point it becomes more a case of which is easier to read/understand etc.

**Comment by TheGreenBandit** [comment]
alright, only problem now is its saying undefined in the hooks even though i have ped.hpp (where i put the functions) included

**Comment by TheGreenBandit** [comment]
btw how would i got about adding hotkeys now as i see the hotkey functions are removed

**Comment by Aure7138** [comment]
check https://github.com/YimMenu/YimMenu/blob/175d93f18aa57f7ef85edebb8620b5aae2bea7d3/src/services/hotkey/hotkey_service.cpp hotkey functions are replaced by command hashes since #725

**Comment by Loko415** [comment]
why are you using open ai to code stuff for you? 💀

**Comment by TheGreenBandit** [comment]
> why are you using open ai to code stuff for you? 💀 

Where are u getting this from?

**Comment by Loko415** [comment]
your discord screenshots and how the code is formatted

**Comment by TheGreenBandit** [comment]
> your discord screenshots and how the code is formatted

Explain to me what is wrong with chat gpt, and no i didnt use it for this, i use it to solve errors or layout ideas.

**Comment by FIying-Scotsman** [comment]
> > your discord screenshots and how the code is formatted
> 
> Explain to me what is wrong with chat gpt, and no i didnt use it for this, i use it to solve errors or layout ideas. You however have threatened to leak my code, leaked part of it, and after i have quit making a menu have just acted hostile

From a coding perspective - it's no different to pasting someone else's code. You'll never learn how it works, or how to fix it if it breaks or even how to improve it because you're relying on whatever training data it used as being correct (a lot of the time it isn't and it's mashing together multiple sources which will work initially but may have hidden issues like memory leaks which you'll never know how to fix because you never wrote it).

From a forum post perspective - it's a lazy way to bump post counts or farm rep, which is why many forums ban or delete posts which use it.

While it's impressive - it's no replacement for doing the work yourself.

**Comment by TheGreenBandit** [comment]
> > > your discord screenshots and how the code is formatted
> 
> > 
> 
> > Explain to me what is wrong with chat gpt, and no i didnt use it for this, i use it to solve errors or layout ideas. You however have threatened to leak my code, leaked part of it, and after i have quit making a menu have just acted hostile
> 
> 
> 
> Unrelated to the topic but from a coding perspective - it's no different to pasting someone else's code. You'll never learn how it works, or how to fix it if it breaks or even how to improve it because you're relying on whatever training data it used as being correct (a lot of the time it isn't and it's mashing together multiple sources which will work initially but may have hidden issues like memory leaks which you'll never know how to fix because you never wrote it).
> 
> 
> 
> From a forum post perspective - it's a lazy way to bump post counts or farm rep, which is why many forums ban or delete posts which use it.
> 
> 
> 
> While it's impressive - it's no replacement for doing the work yourself and is already being abused by people, which is why it's generally looked down upon as just a fancy toy or a way to make quick spam.

Yes, mostly i paste in my code if i have an error i cant solve to get feedback on what is wrong with it then i rewrite the code based off the ai

**Comment by Yimura** [comment]
Implemented in #803
