### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by sean24YT** [YimMenu/YimMenu#819]
### Problem

no

### Solution

no

### Reason

mo

### Additional context

i see you have session commands but i dont understand how they work i googled and whent threw the code and nothing working. if you have custem commands to do like spawn car or give health lmk or if its broken.

**Comment by sch-lda** [comment]
You can browser cpp files in YimMenu/src/views/. In these files you can find code includes "command" like "components::command_checkbox<"keepfixed">();" .Then you can send "/keepfixed" in chat to keep vehicle fixed. Most chat commands' are same as the buttons' name. The only thing you need to do is to add / as prefix
