### ISSUE TITLE
[Request]: Firewall or IP Filter

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#847]
### Problem

Players can spoof RID and player name and bypass block joins. Even if IP is blocked through computer firewall rules, the offending IP address is still able to connect through GTA since it's using their matchmaking server. Sometimes this is enough to pass along attacks remotely. It would be beneficial if their traffic was dumped entirely. 

### Solution

A firewall for GTAO. IP filter or block join based off of IP address and or IP address range. 

### Reason

Another tool to prevent connections that are not desired. 

### Additional context

For example: I have a stalker that randomizes their RID and player name but their IP has been very consistent.

**Comment by Adler-D3R** [comment]
Yup, definitely a good idea.

**Comment by TheGreenBandit** [comment]
you could grab the joining players internal ip and compare it against the blacklist and if its detected as blacklisted could kick them
