### ISSUE TITLE
[Bug]: #602 introduced a bug with vehicles spawned as attachments.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu/YimMenu#901]
### Describe the bug

https://github.com/YimMenu/YimMenu/pull/602/commits/697f8be05a9768619c672a1cd997ee07e3ac53af#diff-8cc7b0ec458e888abba72604fc6516c21d0da3f6bfd4c65c4bc33b31160769d7R134

If you set this to true, the code for attempting to get into vehicles will see these as vehicles the player can get into. If you use the test cases from the original repository you took the code from, there should be a mech or something that Lima_Bean made that constantly caused issues and we had to develop around. The player would constantly try to get into the tank legs. I don't see the purpose for why you would want collision on for these attachments, as it would probably lag the game, but that's not my problem.

### Steps To Reproduce

F

### Expected Behavior

F

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

F

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment]
We could add a check for if the player is in a vehicle then grab the vehicles to set them .(PLAYER::IS_PLAYER_IN_VEHICLE = true)
{
Function
}
