### ISSUE TITLE
[Resolution]

### ISSUE THREAD

**Issue by JDMJay** [YimMenu/YimMenu#923]
### Describe the bug

Was that really needed, was that the optimal way to resolve a 15 year old "paster",
kinda seems like something needs to change in these 1 Lang mfs brains, that's the most extreme thing you could do to a kid. Maybe it was deserved but ye it's not the right way to resolve a situation like that.

### Steps To Reproduce

.

### Expected Behavior

you guys grow up, and stop being little fucking shits.

### Screenshots and/or Logs

.

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by BugisoftRSG** [comment]
He didnt comply with the license
