### ISSUE TITLE
[Request]: Spoof Session Type

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#998]
### Problem

Yimmenu is still vulnerable to remote breakup kicks and remote buttplug kicks. 

### Solution

From what I've gathered from paid menu users this attack is possible to avoid by spoofing session type. 

### Reason

To prevent remote kicks entirely and provide ability to invite friends at the same time. 

### Additional context

NOTE: Yimmenu is capable of preventing remote breakup kicks and remote buttplug kicks but only if RID Join protection is enabled. However, while this is a workaround currently it's not ideal for anyone that wants their friends to be able to join them if they are currently under automated remote kick attacks by individuals that need to get a life. Also it does not appear that the intent of RID Join protection is to prevent remote kicks. I suppose a whitelist capability would also be a solution as well.

**Comment by maybegreat48** [comment]
> Remote buttplug...

...is patched. Only remote breakup remains

You can share your session info with friends which they could join off of

> From what I've gathered from paid menu users this attack is possible to avoid by spoofing session type.

Can you explain further? Unfortunately, remote breakups can only be blocked by the session host if the attacker has your session info (which is obtained through the same RID to session endpoint)

Peer ID randomization may work, which I would look into later

**Comment by maybegreat48** [comment]
Yes, but doing that would prevent your friends from joining too. Spoofing the session info is exactly what YimMenu does
